SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/Contract_Entitlement__c.object-meta.xml
<CustomObject>
    <description>Entitlement line item for a given contract</description>
    <label>Contract Entitlement</label>
    <nameField>
        <label>Contract Entitlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/CPQ_Playbook_Question__c.object-meta.xml
<CustomObject>
    <description>Specific deal question for CPQ quote generation</description>
    <label>CPQ Playbook Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/fields/Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>Answer_Type__c</fullName>
    <description>Type of field where the user will place the question&apos;s answer</description>
    <inlineHelpText>Type of field where Users will place the question&apos;s answer</inlineHelpText>
    <label>Answer Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Multi-Select Picklist</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/fields/Query_String__c.field-meta.xml
<CustomField>
    <fullName>Query_String__c</fullName>
    <description>Query string used to query records. This should NOT include any binded variables. Any dynamic alterations to this query should be handled in a CPQ Rule.</description>
    <inlineHelpText>Query string used to query records. This should NOT include any binded variables. Any dynamic alterations to this query should be handled in a CPQ Rule. Ensure all fields from the Record Display Fields field are also included here.</inlineHelpText>
    <label>Query String</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Criterion__c/CPQ_Playbook_Rule_Criterion__c.object-meta.xml
<CustomObject>
    <description>Criteria to be met for Rule execution</description>
    <label>CPQ Playbook Rule Criterion</label>
    <nameField>
        <label>CPQ Playbook Rule Criterion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Rule Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Criterion__c/fields/CPQ_Playbook_Question__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CPQ Playbook Question from which Criterion gets its evaluation</description>
    <inlineHelpText>Playbook Question from which Criterion gets its evaluation</inlineHelpText>
    <label>CPQ Playbook Question</label>
    <referenceTo>CPQ_Playbook_Question__c</referenceTo>
    <relationshipLabel>CPQ Playbook Rule Criteria</relationshipLabel>
    <relationshipName>CPQ_Playbook_Rule_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Criterion__c/fields/Product_Field__c.field-meta.xml
<CustomField>
    <fullName>Product_Field__c</fullName>
    <description>Field from Product to use for product value. For non-entitlement evaluations, the following CPQ attributes are valid: &apos;Product_Name&apos;, &apos;Start_Date&apos;, &apos;End_Date&apos;, &apos;Quantity&apos;, &apos;Discount&apos;, &apos;Unit_Price&apos;, &apos;List_Price&apos;, &apos;Sub_Total_Price&apos;, and &apos;Total_Price&apos; in addition to any QuoteLineItem Field API names in the event that CPQ is custom stamping said fields. For entitlement evaluations, any Contract_Entitlement__c Field API names are supported.</description>
    <inlineHelpText>Field from Product to use for product value. For non-entitlement evaluations, the following CPQ attributes are valid: &apos;Product_Name&apos;, &apos;Start_Date&apos;, &apos;End_Date&apos;, &apos;Quantity&apos;, &apos;Discount&apos;, &apos;Unit_Price&apos;, &apos;List_Price&apos;, &apos;Sub_Total_Price&apos;, and &apos;Total_Price&apos; in addition to any QuoteLineItem Field API names in the event that CPQ is custom stamping said fields. For entitlement evaluations, any Contract_Entitlement__c Field API names are supported.</inlineHelpText>
    <label>Product Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Criterion__c/fields/Product_Is_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Product_Is_Entitlement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, the product will be evaluated based on how it is configured in its entitlement for the contract being replaced/renewed</description>
    <inlineHelpText>If true, the product will be evaluated based on how it is configured in its entitlement for the contract being replaced/renewed</inlineHelpText>
    <label>Product Is Entitlement</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Criterion__c/fields/Record_Lookup_Field__c.field-meta.xml
<CustomField>
    <fullName>Record_Lookup_Field__c</fullName>
    <description>Field API Name on record that should be accessed for the comparison value.</description>
    <inlineHelpText>Field API Name on record that should be accessed for the comparison value.</inlineHelpText>
    <label>Record Lookup Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/classes/CPQ_Rule_Criterion_UpdatesUtil.cls
/**
* @author Tristan Moser
* @date 4/27/2022
*
* @description CPQ_Playbook_Rule_Criterion__c object Updates class
*
* Tested by CPQ_Record_Validation_Test
*/
public with sharing class CPQ_Rule_Criterion_UpdatesUtil {

    /****************
     * MAIN METHODS
    ****************/

    /**
    * @description All same CPQ_Playbook_Rule_Criterion__c updates that should run on Before Insert AND Before Update
    * @param criteria CPQ_Playbook_Rule_Criterion__c records with updated/inserted values in trigger context
    * @param oldCriteriaMap Map - CPQ_Playbook_Rule_Criterion__c Id to Old version of CPQ_Playbook_Rule_Criterion__c
    */ 
    public static void sameCriterionBeforeUpdates(
        List<CPQ_Playbook_Rule_Criterion__c> criteria,
        Map<Id, CPQ_Playbook_Rule_Criterion__c> oldCriteriaMap
    ) {

        // Related records to query
        RelatedQueryRecords queriedRecords = new RelatedQueryRecords();

        // Gather Question IDs
        Set<Id> questionIDs = new Set<Id>();
        for (CPQ_Playbook_Rule_Criterion__c criterion : criteria) {
            questionIDs.add(criterion.CPQ_Playbook_Question__c);
        }

        // Evaluate each CPQ_Playbook_Rule_Criterion__c
        for (CPQ_Playbook_Rule_Criterion__c criterion : criteria) {

            CPQ_Playbook_Rule_Criterion__c oldCriterion = new CPQ_Playbook_Rule_Criterion__c();
            // Not in Insert context
            if (criterion.Id != null) {
                oldCriterion = oldCriteriaMap.get(criterion.Id);
            }

            // Check for changes in fields that need validation

            // Product Field field or Product Is Entitlement field change
            if (
                (
                    criterion.Product_Field__c != oldCriterion.Product_Field__c ||
                    criterion.Product_Is_Entitlement__c != oldCriterion.Product_Is_Entitlement__c
                ) &&
                criterion.Product_Field__c != null
            ) {

                // QLI/Entitlement distinctions
                List<String> allowedCPQValues = new List<String>();
                String objectName = 'Contract_Entitlement__c';
                if (criterion.Product_Is_Entitlement__c == false) {
                    allowedCPQValues = new List<String>{
                        'Product_Name',
                        'Start_Date',
                        'End_Date',
                        'Quantity',
                        'Discount',
                        'Unit_Price',
                        'List_Price',
                        'Sub_Total_Price',
                        'Total_Price'
                    };
                    objectName = 'QuoteLineItem';
                }

                // Validate Product Field field
                CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyFields(
                    new List<String>{criterion.Product_Field__c},
                    allowedCPQValues,
                    objectName,
                    'Product Field'
                );
                if (results.result == false) {
                    criterion.addError(results.errorMessage);
                }
            }

            // Record Lookup Field field change
            if (criterion.Record_Lookup_Field__c != oldCriterion.Record_Lookup_Field__c &&
                criterion.Record_Lookup_Field__c != null
            ) {

                // Find related question
                CPQ_Playbook_Question__c question = getLookupQuestion(
                    criterion.CPQ_Playbook_Question__c,
                    questionIDs,
                    queriedRecords
                );

                if (question?.Query_String__c != null) {

                    String objectName = question.Query_String__c.toLowerCase().split('from')[1].split(' ')[1];
                    
                    // Validate Default Field Value field
                    CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyFields(
                        new List<String>{criterion.Record_Lookup_Field__c},
                        new List<String>(),
                        objectName,
                        'Record Lookup Field'
                    );
                    if (results.result == false) {
                        criterion.addError(results.errorMessage);
                    }
                }
            }
        }
    }


    /****************
     * QUERY HELPER METHODS
     ****************/

    /**
    * @description Get Question housing record lookup value
    * @param questionId Id of question record
    * @param allQuestionIDs All question IDs for all criterion records in trigger context
    * @param queriedRecords Current state of helper object to determine which related records have been queried
    * @return CPQ_Playbook_Question__c
    */
    private static CPQ_Playbook_Question__c getLookupQuestion(
        Id questionId,
        Set<Id> allQuestionIDs,
        RelatedQueryRecords queriedRecords
    ) {

        // Query question records ONLY if not already queried in this transaction
        if (queriedRecords.lookupQuestions == null) {
            // Define questions map
            queriedRecords.lookupQuestions = new Map<Id, CPQ_Playbook_Question__c>();

            // Query questions
            for (CPQ_Playbook_Question__c q : [
                SELECT Id,
                    Query_String__c
                FROM CPQ_Playbook_Question__c
                WHERE Id IN:allQuestionIDs AND
                    Answer_Type__c = 'Record Lookup'
            ]) {
                queriedRecords.lookupQuestions.put(q.Id, q);
            }
        }

        return queriedRecords.lookupQuestions.get(questionId);
    }

    /**
	* @description Helper object to help store related records to query
	*/ 
    public class RelatedQueryRecords {
        public Map<Id, CPQ_Playbook_Question__c> lookupQuestions;
    }
}