SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/Contract_Entitlement__c.object-meta.xml
<CustomObject>
    <description>Entitlement line item for a given contract</description>
    <label>Contract Entitlement</label>
    <nameField>
        <label>Contract Entitlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product2 record for entitlement</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contract Entitlements</relationshipLabel>
    <relationshipName>Contract_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/CPQ_Playbook_Question__c.object-meta.xml
<CustomObject>
    <description>Specific deal question for CPQ quote generation</description>
    <label>CPQ Playbook Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/fields/Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>Answer_Type__c</fullName>
    <description>Type of field where the user will place the question&apos;s answer</description>
    <inlineHelpText>Type of field where Users will place the question&apos;s answer</inlineHelpText>
    <label>Answer Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Multi-Select Picklist</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/fields/Query_String__c.field-meta.xml
<CustomField>
    <fullName>Query_String__c</fullName>
    <description>Query string used to query records. This should NOT include any binded variables. Any dynamic alterations to this query should be handled in a CPQ Rule.</description>
    <inlineHelpText>Query string used to query records. This should NOT include any binded variables. Any dynamic alterations to this query should be handled in a CPQ Rule. Ensure all fields from the Record Display Fields field are also included here.</inlineHelpText>
    <label>Query String</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Calculation_Item__c/CPQ_Playbook_Rule_Calculation_Item__c.object-meta.xml
<CustomObject>
    <description>Item to be used in Rule Action Calculations</description>
    <label>CPQ Playbook Rule Calculation Item</label>
    <nameField>
        <label>CPQ Playbook  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Rule Calculation Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Calculation_Item__c/fields/CPQ_Playbook_Question__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Question in which answer is taken for calculation</description>
    <inlineHelpText>Question in which answer is taken for calculation</inlineHelpText>
    <label>CPQ Playbook Question</label>
    <referenceTo>CPQ_Playbook_Question__c</referenceTo>
    <relationshipLabel>CPQ Playbook Rule Calculation Items</relationshipLabel>
    <relationshipName>CPQ_Playbook_Rule_Calculation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Calculation_Item__c/fields/Entitlement_Calculation_Field__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Calculation_Field__c</fullName>
    <description>Field name from Entitlement housing calculation value</description>
    <inlineHelpText>Field name from Entitlement housing calculation value. &apos;Contract_Entitlement__c&apos; API fields names are valid. The only valid related object is: &apos;Product__r&apos;.</inlineHelpText>
    <label>Entitlement Calculation Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Calculation_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product in which value is taken for calculation</description>
    <inlineHelpText>Product in which value is taken for calculation</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>CPQ Playbook Rule Calculation Items</relationshipLabel>
    <relationshipName>CPQ_Playbook_Rule_Calculation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Calculation_Item__c/fields/Product_Calculation_Field__c.field-meta.xml
<CustomField>
    <fullName>Product_Calculation_Field__c</fullName>
    <description>Attribute name from Product housing calculation value</description>
    <inlineHelpText>Attribute name from Product housing calculation value. Valid CPQ attributes are: &apos;Start_Date&apos;, &apos;End_Date&apos;, &apos;Quantity&apos;, &apos;Discount&apos;, &apos;Unit_Price&apos;, &apos;List_Price&apos;, &apos;Sub_Total_Price&apos;, and &apos;Total_Price&apos;. Any QuoteLineItem Field API name is also valid given that CPQ has stamped the value. Valid related objects are: &apos;PricebookEntry&apos; and &apos;Product2&apos; (Please enter as object.field).</inlineHelpText>
    <label>Product Calculation Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Calculation_Item__c/fields/Record_Lookup_Field__c.field-meta.xml
<CustomField>
    <fullName>Record_Lookup_Field__c</fullName>
    <description>Field API name from record housing calculation value.</description>
    <inlineHelpText>Field API name from record housing calculation value. Field must be included in the question's query string in order to have a value populated.</inlineHelpText>
    <label>Record Lookup Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/classes/CPQ_Rule_Calculation_Item_UpdatesUtil.cls
/**
* @author Tristan Moser
* @date 4/27/2022
*
* @description CPQ_Playbook_Rule_Calculation_Item__c object Updates class
*
* Tested by CPQ_Record_Validation_Test
*/
public with sharing class CPQ_Rule_Calculation_Item_UpdatesUtil {

    /****************
     * MAIN METHODS
    ****************/

    /**
    * @description All same CPQ_Playbook_Rule_Calculation_Item__c updates that should run on Before Insert AND Before Update
    * @param items CPQ_Playbook_Rule_Calculation_Item__c records with updated/inserted values in trigger context
    * @param oldItemsMap Map - CPQ_Playbook_Rule_Calculation_Item__c Id to Old version of CPQ_Playbook_Rule_Calculation_Item__c
    */ 
    public static void sameItemBeforeUpdates(
        List<CPQ_Playbook_Rule_Calculation_Item__c> items,
        Map<Id, CPQ_Playbook_Rule_Calculation_Item__c> oldItemsMap
    ) {

        // Related records to query
        RelatedQueryRecords queriedRecords = new RelatedQueryRecords();

        // Gather Question IDs
        Set<Id> questionIDs = new Set<Id>();
        for (CPQ_Playbook_Rule_Calculation_Item__c item : items) {
            questionIDs.add(item.CPQ_Playbook_Question__c);
        }
        

        // Evaluate each CPQ_Playbook_Rule_Calculation_Item__c
        for (CPQ_Playbook_Rule_Calculation_Item__c item : items) {

            CPQ_Playbook_Rule_Calculation_Item__c oldItem = new CPQ_Playbook_Rule_Calculation_Item__c();
            // Not in Insert context
            if (item.Id != null) {
                oldItem = oldItemsMap.get(item.Id);
            }

            // Check for changes in fields that need validation

            // Product Calculation Field field change
            if (
                item.Product_Calculation_Field__c != oldItem.Product_Calculation_Field__c &&
                item.Product_Calculation_Field__c != null
            ) {

                // QLI Field
                if (item.Product_Calculation_Field__c.split('\\.').size() == 1) {

                    // Validate Product Calculation Field field
                    CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyFields(
                        new List<String>{item.Product_Calculation_Field__c},
                        new List<String>{
                            'Start_Date',
                            'End_Date',
                            'Quantity',
                            'Discount',
                            'Unit_Price',
                            'List_Price',
                            'Sub_Total_Price',
                            'Total_Price'
                        },
                        'QuoteLineItem',
                        'Product Calculation Field'
                    );
                    if (results.result == false) {
                        item.addError(results.errorMessage);
                    }
                }

                // PricebookEntry/Product2 Field
                else {

                    // Validate Product Calculation Field field
                    CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyObjectFieldPair(
                        item.Product_Calculation_Field__c,
                        new Map<String, String>{
                            'PricebookEntry' => 'PricebookEntry',
                            'Product2' => 'Product2'
                        },
                        'Product Calculation Field'
                    );
                    if (results.result == false) {
                        item.addError(results.errorMessage);
                    }
                }
            }

            // Entitlement Calculation Field field change
            if (
                item.Entitlement_Calculation_Field__c != oldItem.Entitlement_Calculation_Field__c &&
                item.Entitlement_Calculation_Field__c != null
            ) {

                // Contract_Entitlement__c Field
                if (item.Entitlement_Calculation_Field__c.split('\\.').size() == 1) {

                    // Validate Entitlement Calcluation Field field
                    CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyFields(
                        new List<String>{item.Entitlement_Calculation_Field__c},
                        new List<String>(),
                        'Contract_Entitlement__c',
                        'Entitlement Calculation Field'
                    );
                    if (results.result == false) {
                        item.addError(results.errorMessage);
                    }
                }

                // Product2 Field
                else {

                    // Validate Product Field field
                    CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyObjectFieldPair(
                        item.Entitlement_Calculation_Field__c,
                        new Map<String, String>{
                            'Product__r' => 'Product2'
                        },
                        'Entitlement Calculation Field'
                    );
                    if (results.result == false) {
                        item.addError(results.errorMessage);
                    }
                }
            }

            // Record Lookup Field field change
            if (item.Record_Lookup_Field__c != oldItem.Record_Lookup_Field__c &&
                item.Record_Lookup_Field__c != null
            ) {

                // Find related question
                CPQ_Playbook_Question__c question = getLookupQuestion(
                    item.CPQ_Playbook_Question__c,
                    questionIDs,
                    queriedRecords
                );

                if (question?.Query_String__c != null) {

                    String objectName = question.Query_String__c.toLowerCase().split('from')[1].split(' ')[1];
                    
                    // Validate Default Field Value field
                    CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyFields(
                        new List<String>{item.Record_Lookup_Field__c},
                        new List<String>(),
                        objectName,
                        'Record Lookup Field'
                    );
                    if (results.result == false) {
                        item.addError(results.errorMessage);
                    }
                }
            }
        }
    }

    /****************
     * QUERY HELPER METHODS
     ****************/

    /**
    * @description Get Question housing record lookup value
    * @param questionId Id of question record
    * @param allQuestionIDs All question IDs for all item records in trigger context
    * @param queriedRecords Current state of helper object to determine which related records have been queried
    * @return CPQ_Playbook_Question__c
    */
    private static CPQ_Playbook_Question__c getLookupQuestion(
        Id questionId,
        Set<Id> allQuestionIDs,
        RelatedQueryRecords queriedRecords
    ) {

        // Query question records ONLY if not already queried in this transaction
        if (queriedRecords.lookupQuestions == null) {
            // Define questions map
            queriedRecords.lookupQuestions = new Map<Id, CPQ_Playbook_Question__c>();

            // Query questions
            for (CPQ_Playbook_Question__c q : [
                SELECT Id,
                    Query_String__c
                FROM CPQ_Playbook_Question__c
                WHERE Id IN:allQuestionIDs AND
                    Answer_Type__c = 'Record Lookup'
            ]) {
                queriedRecords.lookupQuestions.put(q.Id, q);
            }
        }

        return queriedRecords.lookupQuestions.get(questionId);
    }

    /**
	* @description Helper object to help store related records to query
	*/ 
    public class RelatedQueryRecords {
        public Map<Id, CPQ_Playbook_Question__c> lookupQuestions;
    }
}