SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/Adjusted_by_Contract__c.field-meta.xml
<CustomField>
    <fullName>Adjusted_by_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that holds the contract&apos;s adjustment</description>
    <label>Adjusted by Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Source Contracts</relationshipLabel>
    <relationshipName>Source_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/Adjustment_of_Contract__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_of_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract of which contract is an adjustment</description>
    <label>Adjustment of Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Adjustments</relationshipLabel>
    <relationshipName>Contract_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/Adjustment_Type__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Type__c</fullName>
    <description>Type of Contract Adjustment the Contract performed</description>
    <inlineHelpText></inlineHelpText>
    <label>Adjustment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>Latest end date of Contract Entitlements</description>
    <label>Contract End Date</label>
    <summarizedField>Contract_Entitlement__c.End_Date__c</summarizedField>
    <summaryForeignKey>Contract_Entitlement__c.Contract__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>Earliest start date of Contract Entitlements</description>
    <label>Contract Start Date</label>
    <summarizedField>Contract_Entitlement__c.Start_Date__c</summarizedField>
    <summaryForeignKey>Contract_Entitlement__c.Contract__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/CPQ_Playbook__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Playbook used to configure contract</description>
    <label>CPQ Playbook</label>
    <referenceTo>CPQ_Playbook__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/Contract_Entitlement__c.object-meta.xml
<CustomObject>
    <description>Entitlement line item for a given contract</description>
    <label>Contract Entitlement</label>
    <nameField>
        <label>Contract Entitlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Contract to which the entitlement belongs</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Entitlements</relationshipLabel>
    <relationshipName>Contract_Entitlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/CPQ_Playbook_Rule_Action__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook_Rule_Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Action that added this Entitlement Line Item</description>
    <label>CPQ Playbook Rule Action</label>
    <referenceTo>CPQ_Playbook_Rule_Action__c</referenceTo>
    <relationshipLabel>Contract Entitlements</relationshipLabel>
    <relationshipName>Contract_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount percentage</description>
    <label>Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of entitlement</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>Original list price before any pricing adjustments</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product2 record for entitlement</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contract Entitlements</relationshipLabel>
    <relationshipName>Contract_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Number of units of entitlement</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of entitlement</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Quantity__c * Unit_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Price after any pricing adjustments</description>
    <label>Unit Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Playbook_Answer__c/Contract_Playbook_Answer__c.object-meta.xml
<CustomObject>
    <description>Houses responses/answers to a specific CPQ Playbook Question</description>
    <label>Contract Playbook Answer</label>
    <nameField>
        <label>Contract Playbook Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Playbook Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Playbook_Answer__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Parent Contract record</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Playbook Answers</relationshipLabel>
    <relationshipName>Contract_Playbook_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/CPQ_Playbook__c.object-meta.xml
<CustomObject>
    <description>Set of deal questions for CPQ quote generation. Unique path for different opportunity types</description>
    <label>CPQ Playbook</label>
    <nameField>
        <label>CPQ Playbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Entitlement_Summary_Columns__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Summary_Columns__c</fullName>
    <description>Semicolon delineated list of field API names on the Contract_Entitlement__c object to be shown in the Entitlement Summary view in CPQ. Any Contract_Entitlement__c Custom Field API names are supported.</description>
    <inlineHelpText>Semicolon delineated list of field API names on the Contract_Entitlement__c object to be shown in the Entitlement Summary view in CPQ. Any Contract_Entitlement__c Custom Field API names are supported.</inlineHelpText>
    <label>Entitlement Summary Columns</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if playbook is active and should appear in CPQ</description>
    <inlineHelpText>Determines if playbook is active and should appear in CPQ</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/CPQ_Playbook_Question__c.object-meta.xml
<CustomObject>
    <description>Specific deal question for CPQ quote generation</description>
    <label>CPQ Playbook Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if question is active and should appear in its group</description>
    <inlineHelpText>Determines if question is active and should appear in its group</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question_Group__c/CPQ_Playbook_Question_Group__c.object-meta.xml
<CustomObject>
    <description>Container for CPQ Playbook Questions</description>
    <label>CPQ Playbook Question Group</label>
    <nameField>
        <label>CPQ Playbook Question Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Question Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question_Group__c/fields/CPQ_Playbook__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook__c</fullName>
    <description>CPQ Playbook to which this question group belongs</description>
    <inlineHelpText>CPQ Playbook to which this question group belongs</inlineHelpText>
    <label>CPQ Playbook</label>
    <referenceTo>CPQ_Playbook__c</referenceTo>
    <relationshipLabel>CPQ Playbook Question Groups</relationshipLabel>
    <relationshipName>CPQ_Playbook_Question_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question_Group__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if group is active and should appear in its CPQ Playbook</description>
    <inlineHelpText>Determines if group is active and should appear in its CPQ Playbook</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Action__c/CPQ_Playbook_Rule_Action__c.object-meta.xml
<CustomObject>
    <description>Action to be run upon successful Rule evaluation</description>
    <label>CPQ Playbook Rule Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Action__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if action is active and should be executed in rule</description>
    <inlineHelpText>Determines if action is active and should be executed in rule</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Action__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product2 record that will be acted upon</description>
    <inlineHelpText>Product2 record that will be acted upon</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>CPQ Playbook Rule Actions</relationshipLabel>
    <relationshipName>CPQ_Playbook_Rule_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/objects-layouts/main/default/objects/Opportunity/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>IF(
AND(today()&gt;= Effective_service_date__c , today()&lt;= Actual_service_end_date__c ),TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/objects-layouts/main/default/objects/Opportunity/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>list of all product name pulled from the product table through rollup helper</description>
    <label>Product Name</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/classes/cpq_ContractsByAccountClass.cls
/**
* @author Tristan Moser
* @date 2/25/2022
*
* @description Contracts by Account controller class
*
* Tested by cpq_ContractsByAccountClassTest
*/
public with sharing class cpq_ContractsByAccountClass {

    /**
    * @description Query Account so that is appears under recently viewed
    * @param acctId Id of Account record
    */
    @AuraEnabled
    public static void queryAccount(Id acctId) {
        Account acct = [
            SELECT Id
            FROM Account
            WHERE Id=:acctId
            FOR VIEW
        ];
    }

    /**
    * @description Query recently viewed account records
    * @return List of recently viewed account records
    */
    @AuraEnabled
    public static List<Account> getRecentlyViewed() {
        Set<Id> recentlyViewedAcctIDs = new Set<Id>();
        for (RecentlyViewed rv : [
            SELECT Id
            FROM RecentlyViewed
            WHERE Type='Account'
        ]) {
            recentlyViewedAcctIDs.add(rv.Id);
        }

        List<Account> accounts = new List<Account>();
        accounts = [
            SELECT Id,
                Name,
                Owner.Name,
                LastViewedDate
            FROM Account
            WHERE Id IN:recentlyViewedAcctIDs
            ORDER BY LastViewedDate DESC
        ];

        return accounts;
    }

    /**
    * @description Query account with related contracts
    * @param acctId Id of Account record
    * @return AccountObj for given account
    */
    @AuraEnabled
    public static AccountObj queryAccountWithContracts(Id acctId) {

        Boolean multiCurrency = System.UserInfo.isMultiCurrencyOrganization();

        AccountObj acctObj = new AccountObj();

        acctObj.acctInfo = [
            SELECT Id,
                Name,
                Owner.Name
            FROM Account
            WHERE Id =:acctId
        ];

        // Contract Entitlement Fields
        Set<String> entitlementFields = new Set<String>{
            'Id',
            'CPQ_Playbook_Rule_Action__c',
            'Discount__c',
            'End_Date__c',
            'List_Price__c',
            'Product__c',
            'Product_Name__c',
            'Quantity__c',
            'Start_Date__c',
            'Total_Price__c',
            'Unit_Price__c'
        };
        // Query all active playbooks
        for (CPQ_Playbook__c playbook : [
            SELECT Id,
                Entitlement_Summary_Columns__c
            FROM CPQ_Playbook__c
            WHERE IsActive__c=true AND
                Entitlement_Summary_Columns__c != null
        ]) {
            // Extract each field
            for (String field : playbook.Entitlement_Summary_Columns__c.split(';')) {

                entitlementFields.add(field);
            }
        }
        // Convert Set to String
        String entitlementFieldsString = '';
        for (String field : entitlementFields) {
            entitlementFieldsString += field + ',';
        }
        entitlementFieldsString = entitlementFieldsString.removeEnd(',');

        // Query Contracts
        acctObj.Contracts = new List<Contract>();
        String contractQuery = ''
            + 'SELECT Id, '
                + 'Adjusted_by_Contract__c, '
                + 'Adjusted_by_Contract__r.ContractNumber, '
                + 'Adjustment_of_Contract__c, '
                + 'Adjustment_of_Contract__r.ContractNumber, '
                + 'Adjustment_Type__c, '
                + 'Contract_End_Date__c, '
                + 'ContractNumber, '
                + 'Contract_Start_Date__c, '
                + 'Contract_Status__c, '
                + 'Contract_Total__c, '
                + 'CPQ_Playbook__c, '
                + 'CPQ_Playbook__r.Default_Term_in_Months__c, '
                + 'CPQ_Playbook__r.Label__c, '
                + 'CPQ_Playbook__r.Pricebook__c, '
                + 'Opportunity__c, '
                + 'Opportunity__r.Name, '
                + 'Quote__c, '
                + (multiCurrency == true ? 'CurrencyIsoCode, ' : '')
                + '( '
                    + 'SELECT '
                        + entitlementFieldsString
                    + ' FROM Contract_Entitlements__r '
                + '), '
                + '( '
                    + 'SELECT Id, '
                        + 'CPQ_Playbook_Question__c, '
                        + 'CPQ_Playbook_Question__r.CPQ_Playbook_Question_Group__c, '
                        + 'CPQ_Playbook_Question__r.CPQ_Playbook_Question_Group__r.CPQ_Playbook__c, '
                        + 'Value_Boolean__c, '
                        + 'Value_Currency__c, '
                        + 'Value_Date__c, '
                        + 'Value_Decimal__c, '
                        + 'Value_Integer__c, '
                        + 'Value_Text__c'
                    + ' FROM Contract_Playbook_Answers__r'
                + ') '
            + 'FROM Contract '
            + 'WHERE AccountId =:acctId '
            + 'ORDER BY Contract_Start_Date__c DESC, '
                + 'Contract_End_Date__c DESC, '
                + 'ContractNumber ';
        acctObj.Contracts = Database.query(contractQuery);

        if (multiCurrency == true) {
            List<sObject> currencies = new List<sObject>();
            currencies = Database.query('SELECT Id, ConversionRate, IsoCode FROM CurrencyType WHERE IsActive = TRUE AND IsCorporate = TRUE');
            if (currencies.size() > 0) {
                acctObj.defaultCurrency = (String) currencies[0].get('IsoCode');
            }   
        }
        
        if (acctObj.defaultCurrency == null) {
            acctObj.defaultCurrency = System.UserInfo.getDefaultCurrency();
        }

        return acctObj;
    }

    public class AccountObj {
        @AuraEnabled public Account acctInfo;
        @AuraEnabled public List<Contract> Contracts;
        @AuraEnabled public String defaultCurrency;
    }

    /**
    * @description Generic method to update a list of sObject records
    * @param records List of sObject records
    */
    @AuraEnabled
    public static void updateRecords(List<sObject> records) {
        update records;
    }
}