SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/Adjustment_of_Contract__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_of_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract of which contract is an adjustment</description>
    <label>Adjustment of Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Adjustments</relationshipLabel>
    <relationshipName>Contract_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/Adjustment_Type__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Type__c</fullName>
    <description>Type of Contract Adjustment the Contract performed</description>
    <inlineHelpText></inlineHelpText>
    <label>Adjustment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/CPQ_Playbook__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Playbook used to configure contract</description>
    <label>CPQ Playbook</label>
    <referenceTo>CPQ_Playbook__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original Opportunity that generated contract</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original Synced Quote that generated the contract</description>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/Contract_Entitlement__c.object-meta.xml
<CustomObject>
    <description>Entitlement line item for a given contract</description>
    <label>Contract Entitlement</label>
    <nameField>
        <label>Contract Entitlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Contract to which the entitlement belongs</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Entitlements</relationshipLabel>
    <relationshipName>Contract_Entitlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/CPQ_Playbook_Rule_Action__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook_Rule_Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Action that added this Entitlement Line Item</description>
    <label>CPQ Playbook Rule Action</label>
    <referenceTo>CPQ_Playbook_Rule_Action__c</referenceTo>
    <relationshipLabel>Contract Entitlements</relationshipLabel>
    <relationshipName>Contract_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount percentage</description>
    <label>Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of entitlement</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>Original list price before any pricing adjustments</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product2 record for entitlement</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contract Entitlements</relationshipLabel>
    <relationshipName>Contract_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Number of units of entitlement</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original Quote Line Item that generated entitlement</description>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Contract Entitlements</relationshipLabel>
    <relationshipName>Contract_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of entitlement</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Price after any pricing adjustments</description>
    <label>Unit Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Playbook_Answer__c/Contract_Playbook_Answer__c.object-meta.xml
<CustomObject>
    <description>Houses responses/answers to a specific CPQ Playbook Question</description>
    <label>Contract Playbook Answer</label>
    <nameField>
        <label>Contract Playbook Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Playbook Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Playbook_Answer__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Parent Contract record</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Playbook Answers</relationshipLabel>
    <relationshipName>Contract_Playbook_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Answer__c/CPQ_Playbook_Answer__c.object-meta.xml
<CustomObject>
    <description>Child of Quote object. Houses responses/answers to a specific CPQ Playbook Question</description>
    <label>CPQ Playbook Answer</label>
    <nameField>
        <label>Playbook Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Answer__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <description>Parent Quote record</description>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>CPQ Playbook Answers</relationshipLabel>
    <relationshipName>CPQ_Playbook_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Action__c/CPQ_Playbook_Rule_Action__c.object-meta.xml
<CustomObject>
    <description>Action to be run upon successful Rule evaluation</description>
    <label>CPQ Playbook Rule Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Action__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product2 record that will be acted upon</description>
    <inlineHelpText>Product2 record that will be acted upon</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>CPQ Playbook Rule Actions</relationshipLabel>
    <relationshipName>CPQ_Playbook_Rule_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Opportunity/fields/Create_Contract__c.field-meta.xml
<CustomField>
    <fullName>Create_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automation flag to create Contract and Entitlements based on Synced Quote.</description>
    <inlineHelpText>Automation flag to create Contract and Entitlements based on Synced Quote.</inlineHelpText>
    <label>Create Contract</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/Adjustment_of_Contract__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_of_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract of which quote is an adjustment</description>
    <label>Adjustment of Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Quote Adjustments</relationshipLabel>
    <relationshipName>Quote_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/Adjustment_Type__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Type__c</fullName>
    <description>Type of Contract Adjustment the Quote outlines</description>
    <inlineHelpText></inlineHelpText>
    <label>Adjustment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/CPQ_Playbook__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Playbook used to configure quote in CPQ</description>
    <label>CPQ Playbook</label>
    <referenceTo>CPQ_Playbook__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Latest end date of Quote Line Items</description>
    <label>End Date</label>
    <summarizedField>QuoteLineItem.End_Date__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Earliest start date of Quote Line Items</description>
    <label>Start Date</label>
    <summarizedField>QuoteLineItem.Start_Date__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/QuoteLineItem/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Percent change from List Price to Unit Price</description>
    <label>Discount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/QuoteLineItem/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>Original Price determined by pricebook entry</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/QuoteLineItem/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Order Quantity</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/QuoteLineItem/fields/Quoted_Price__c.field-meta.xml
<CustomField>
    <fullName>Quoted_Price__c</fullName>
    <description>Actual price per unit of quantity</description>
    <label>Quoted Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/QuoteLineItem/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Actual price per unit of quantity</description>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/classes/OppContractUtil.cls
public class OppContractUtil {

    /****************
     * ENTRY METHODS
    ****************/

    /**
    * @description Logic run after an Opportunity Insert
    * Handles updates of related records
    * @param insertedOpps Opportunity records with inserted values in trigger context
    */ 
    public static void processAfterInsert(
        List<Opportunity> insertedOpps
    ) {
        relatedObjectAfterUpdates(
            insertedOpps,
            new Map<Id, Opportunity>()
        );
    }

    /**
    * @description Logic run after an Opportunity Update
    * Handles updates of related records
    * @param updatedOpps Opportunity records with updated values in trigger context
    * @param oldOppsMap Map - Opportunity Id to Old version of Opportunity
    */ 
    public static void processAfterUpdate(
        List<Opportunity> updatedOpps,
        Map<Id, Opportunity> oldOppsMap
    ) {
        relatedObjectAfterUpdates(
            updatedOpps,
            oldOppsMap
        );
    }

    /****************
     * MAIN METHODS
    ****************/

    /**
    * @description All same Related Object updates that should run on After Insert AND After Update
    * @param opps Opportunity records with updated/inserted values in trigger context
    * @param oldOppsMap Map - Opportunity Id to Old version of Opportunity
    */ 
    public static void relatedObjectAfterUpdates(
        List<Opportunity> opps,
        Map<Id, Opportunity> oldOppsMap
    ) {

        // Gather Related IDs that may be needed
        Set<Id> syncedQuoteIDs = new Set<Id>();
        for (Opportunity opp : opps) {
            syncedQuoteIDs.add(opp.SyncedQuoteId);
        }

        // Related records to query
        RelatedQueryRecords queriedRecords = new RelatedQueryRecords();

        // Contract records to insert
        List<Contract> contractsToInsert = new List<Contract>();

        // Opp to Contract Adjustment Type
        Map<Id, String> adjTypeMap = new Map<Id, String>();

        // Contract Entitlement records to insert
        Map<Id, List<Contract_Entitlement__c>> entitlementsToInsert = new Map<Id, List<Contract_Entitlement__c>>();

        // Contract Playbook Answer records to insert
        Map<Id, List<Contract_Playbook_Answer__c>> answersToInsert = new Map<Id, List<Contract_Playbook_Answer__c>>();

        // Evaluate each Opportunity
        for (Opportunity opp : opps) {

            // Get Old version of Opportunity
            Opportunity oldOpp = new Opportunity();
            // Not in Insert context
            if (oldOppsMap.containsKey(opp.Id)) {
                oldOpp = oldOppsMap.get(opp.Id);
            }

            // Opp Create Contract flag tripped
            if (opp.Create_Contract__c == true &&
                oldOpp.Create_Contract__c != true
            ) {

                // Synced Quote exists
                if (opp.SyncedQuoteId != null) {

                    // Get Synced Quote
                    Quote syncedQuote = getSyncedQuote(
                        opp.SyncedQuoteId,
                        syncedQuoteIDs,
                        queriedRecords
                    );

                    // Generate new Contract
                    Contract newCont = new Contract();
                    newCont.AccountId = opp.AccountId;
                    newCont.Opportunity__c = opp.Id;
                    newCont.Quote__c = opp.SyncedQuoteId;
                    newCont.CPQ_Playbook__c = syncedQuote.CPQ_Playbook__c;

                    // Contract being adjusted (if applicable)
                    newCont.Adjustment_of_Contract__c = syncedQuote.Adjustment_of_Contract__c;

                    // Adjustment Type (if applicable)
                    adjTypeMap.put(opp.Id, syncedQuote.Adjustment_Type__c);

                    // Generate new Contract Entitlements
                    Date startDate;
                    Date endDate;
                    for (QuoteLineItem qli : syncedQuote.QuoteLineItems) {

                        // New Entitlement
                        Contract_Entitlement__c ent = new Contract_Entitlement__c();
                        ent.Quote_Line_Item__c = qli.Id;
                        ent.Discount__c = qli.Discount__c;
                        ent.End_Date__c = qli.End_Date__c;
                        ent.List_Price__c = qli.List_Price__c;
                        ent.Product__c = qli.Product2Id;
                        ent.Quantity__c = qli.Quantity__c;
                        ent.Start_Date__c = qli.Start_Date__c;
                        ent.Unit_Price__c = qli.Quoted_Price__c;
                        ent.CPQ_Playbook_Rule_Action__c = qli.CPQ_Playbook_Rule_Action__c;

                        if (!entitlementsToInsert.containsKey(opp.Id)) {
                            entitlementsToInsert.put(opp.Id, new List<Contract_Entitlement__c>());
                        }

                        entitlementsToInsert.get(opp.Id).add(ent);

                        // Update contract dates
                        if (startDate == null ||
                            ent.Start_Date__c < startDate
                        ) {
                            startDate = ent.Start_Date__c;
                        }
                        if (endDate == null ||
                            ent.End_Date__c > endDate
                        ) {
                            endDate = ent.End_Date__c;
                        }
                    }

                    // Update Standard dates
                    newCont.StartDate = startDate;
                    newCont.ContractTerm = startDate.monthsBetween(endDate);
                    if (newCont.ContractTerm <= 0) {
                        newCont.ContractTerm = 1;
                    }

                    // Generate new Contract Playbook Answers
                    for (CPQ_Playbook_Answer__c answer : syncedQuote.CPQ_Playbook_Answers__r) {

                        // New Answer
                        Contract_Playbook_Answer__c ans = new Contract_Playbook_Answer__c();
                        ans.CPQ_Playbook_Question__c = answer.CPQ_Playbook_Question__c;
                        ans.Name = answer.Name;
                        ans.Value_Boolean__c = answer.Value_Boolean__c;
                        ans.Value_Currency__c = answer.Value_Currency__c;
                        ans.Value_Date__c = answer.Value_Date__c;
                        ans.Value_Decimal__c = answer.Value_Decimal__c;
                        ans.Value_Integer__c = answer.Value_Integer__c;
                        ans.Value_Text__c = answer.Value_Text__c;

                        if (!answersToInsert.containsKey(opp.Id)) {
                            answersToInsert.put(opp.Id, new List<Contract_Playbook_Answer__c>());
                        }

                        answersToInsert.get(opp.Id).add(ans);
                    }

                    contractsToInsert.add(newCont);

                }
            }
        }

        // Insert contracts if present
        if (contractsToInsert.size() > 0) {

            // Insert records
            insert contractsToInsert;

            List<Contract_Entitlement__c> entitlements = new List<Contract_Entitlement__c>();
            List<Contract_Playbook_Answer__c> answers = new List<Contract_Playbook_Answer__c>();

            List<Contract> adjustedContracts = new List<Contract>();

            // Relate contracts to entitlements and answers
            for (Contract cont : contractsToInsert) {

                // Get Entitlements
                for (Contract_Entitlement__c ent : entitlementsToInsert.get(cont.Opportunity__c)) {
                    ent.Contract__c = cont.Id;

                    entitlements.add(ent);
                }

                // Get Answers
                for (Contract_Playbook_Answer__c answer : answersToInsert.get(cont.Opportunity__c)) {
                    answer.Contract__c = cont.Id;

                    answers.add(answer);
                }

                // Update source contract
                if (cont.Adjustment_of_Contract__c != null) {
                    Contract adjustedContract = new Contract(
                        Id=cont.Adjustment_of_Contract__c,
                        Adjusted_by_Contract__c=cont.Id
                    );

                    if (adjTypeMap.get(cont.Opportunity__c) == 'Replacement') {
                        adjustedContract.IsReplaced__c = true;
                    }

                    adjustedContracts.add(adjustedContract);
                }
            }

            if (entitlements.size() > 0) {
                insert entitlements;
            }

            if (answers.size() > 0) {
                insert answers;
            }

            if (adjustedContracts.size() > 0) {
                update adjustedContracts;
            }
        }
    }


    /****************
     * QUERY HELPER METHODS
     ****************/

    /**
    * @description Get Synced Quote record for a given Opportunity
    * @param syncedQuoteId Synced Quote Id of Opportunity record is needed for
    * @param allSyncedQuoteIDs All Synced Quote IDs for all Opportunity records in trigger context
    * @param queriedRecords Current state of helper object to determine which related records have been queried
    * @return Quote
    */
    private static Quote getSyncedQuote(
        Id syncedQuoteId,
        Set<Id> allSyncedQuoteIDs,
        RelatedQueryRecords queriedRecords
    ) {

        // Query Quote records ONLY if not already queried in this transaction
        if (queriedRecords.syncedQuotes == null) {
            // Define Synced Quotes map
            queriedRecords.syncedQuotes = new Map<Id, Quote>();
            // Query and organize Steps by Opportunity
            for (Quote q : [
                SELECT Id,
                    Adjustment_of_Contract__c,
                    Adjustment_Type__c,
                    CPQ_Playbook__c,
                    (
                        SELECT Id,
                            CPQ_Playbook_Rule_Action__c,
                            Discount__c,
                            End_Date__c,
                            List_Price__c,
                            Product2Id,
                            Product2.Do_Not_Create_Entitlement__c,
                            Quantity__c,
                            Quoted_Price__c,
                            Start_Date__c,
                            TotalPrice
                        FROM QuoteLineItems
                        WHERE Product2.Do_Not_Create_Entitlement__c != true
                    ),
                    (
                        SELECT Id,
                            CPQ_Playbook_Question__c,
                            Name,
                            Value_Boolean__c,
                            Value_Currency__c,
                            Value_Date__c,
                            Value_Decimal__c,
                            Value_Integer__c,
                            Value_Text__c
                        FROM CPQ_Playbook_Answers__r
                    )
                FROM Quote
                WHERE Id IN:allSyncedQuoteIDs
            ]) {
                queriedRecords.syncedQuotes.put(q.Id, q);
            }
        }

        return queriedRecords.syncedQuotes.get(syncedQuoteId);
    }

    /**
	* @description Helper object to help store related records to query
	*/ 
    public class RelatedQueryRecords {
        public Map<Id, Quote> syncedQuotes;
    }
}