SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>Earliest start date of Contract Entitlements</description>
    <label>Contract Start Date</label>
    <summarizedField>Contract_Entitlement__c.Start_Date__c</summarizedField>
    <summaryForeignKey>Contract_Entitlement__c.Contract__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/Contract_Total__c.field-meta.xml
<CustomField>
    <fullName>Contract_Total__c</fullName>
    <description>Total contract currency value</description>
    <label>Contract Total</label>
    <summarizedField>Contract_Entitlement__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Contract_Entitlement__c.Contract__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/CPQ_Playbook__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Playbook used to configure contract</description>
    <label>CPQ Playbook</label>
    <referenceTo>CPQ_Playbook__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/IsVoid__c.field-meta.xml
<CustomField>
    <fullName>IsVoid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if contract has been voided</description>
    <label>Is Void</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/CPQ_Playbook__c.object-meta.xml
<CustomObject>
    <description>Set of deal questions for CPQ quote generation. Unique path for different opportunity types</description>
    <label>CPQ Playbook</label>
    <nameField>
        <label>CPQ Playbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Default_Term_in_Months__c.field-meta.xml
<CustomField>
    <fullName>Default_Term_in_Months__c</fullName>
    <description>Default term of quote in months</description>
    <inlineHelpText>Default term of quote in months</inlineHelpText>
    <label>Default Term (in Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Entitlement_Summary_Columns__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Summary_Columns__c</fullName>
    <description>Semicolon delineated list of field API names on the Contract_Entitlement__c object to be shown in the Entitlement Summary view in CPQ. Any Contract_Entitlement__c Custom Field API names are supported.</description>
    <inlineHelpText>Semicolon delineated list of field API names on the Contract_Entitlement__c object to be shown in the Entitlement Summary view in CPQ. Any Contract_Entitlement__c Custom Field API names are supported.</inlineHelpText>
    <label>Entitlement Summary Columns</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if playbook is active and should appear in CPQ</description>
    <inlineHelpText>Determines if playbook is active and should appear in CPQ</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Displayed label in CPQ</description>
    <inlineHelpText>Displayed label Users see in CPQ</inlineHelpText>
    <label>Label</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Pricebook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pricebook used for products added in playbook</description>
    <inlineHelpText>Pricebook from which products are pulled from for rules</inlineHelpText>
    <label>Pricebook</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>CPQ Playbooks</relationshipLabel>
    <relationshipName>CPQ_Playbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Product_Summary_Columns__c.field-meta.xml
<CustomField>
    <fullName>Product_Summary_Columns__c</fullName>
    <description>Semicolon delineated list of attribute names on the Product level to be shown in the Product Summary view in CPQ. The following CPQ attributes are valid: &apos;Product_Name&apos;, &apos;Start_Date&apos;, &apos;End_Date&apos;, &apos;Quantity&apos;, &apos;Discount&apos;, &apos;Unit_Price&apos;, &apos;List_Price&apos;, &apos;Sub_Total_Price&apos;, and &apos;Total_Price&apos;. Any QuoteLineItem Field API names are also supported in the event that CPQ is custom stamping said fields.</description>
    <inlineHelpText>List of attribute names on the Product level to be shown in the Product Summary view in CPQ. The following CPQ attributes are valid: &apos;Product_Name&apos;, &apos;Start_Date&apos;, &apos;End_Date&apos;, &apos;Quantity&apos;, &apos;Discount&apos;, &apos;Unit_Price&apos;, &apos;List_Price&apos;, &apos;Sub_Total_Price&apos;, and &apos;Total_Price&apos;. Any QuoteLineItem Field API names are also supported in the event that CPQ is custom stamping said fields.</inlineHelpText>
    <label>Product Summary Columns</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Proposal_Footer__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Footer__c</fullName>
    <description>Footer display for Proposal PDF</description>
    <inlineHelpText>Footer display for Proposal PDF (Will not appear on the first page)</inlineHelpText>
    <label>Proposal Footer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Proposal_Header__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Header__c</fullName>
    <description>Header display for Proposal PDF</description>
    <inlineHelpText>Header display for Proposal PDF (Will not appear on the first page)</inlineHelpText>
    <label>Proposal Header</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Proposal_Header_Type__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Header_Type__c</fullName>
    <description>Determines if Proposal Header will display from an attached image or from the rich text field</description>
    <inlineHelpText>Determines if Proposal Header will display from an attached image or from the rich text field</inlineHelpText>
    <label>Proposal Header Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_System_Settings__c/CPQ_System_Settings__c.object-meta.xml
<CustomObject>
    <description>CPQ System Configuration Settings</description>
    <label>CPQ System Settings</label>
    <nameField>
        <label>CPQ System Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ System Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_System_Settings__c/fields/Contract_Table_Actions__c.field-meta.xml
<CustomField>
    <fullName>Contract_Table_Actions__c</fullName>
    <description>Contract actions CPQ users have available</description>
    <inlineHelpText>Contract actions CPQ users have available</inlineHelpText>
    <label>Contract Table Actions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>View</fullName>
            </value>
            <value>
                <fullName>Amend</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Renew</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_System_Settings__c/fields/Contract_Table_Columns__c.field-meta.xml
<CustomField>
    <fullName>Contract_Table_Columns__c</fullName>
    <description>Semicolon delineated list of field API names on the Contract object to be shown in the Contract Table view in CPQ. Any Contract Field API names are supported.</description>
    <inlineHelpText>Semicolon delineated list of field API names on the Contract object to be shown in the Contract Table view in CPQ. Any Contract Field API names are supported.</inlineHelpText>
    <label>Contract Table Columns</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_System_Settings__c/fields/Default_Playbook__c.field-meta.xml
<CustomField>
    <fullName>Default_Playbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Default playbook to be used when creating a new quote</description>
    <inlineHelpText>Default playbook to be used when creating a new quote</inlineHelpText>
    <label>Default Playbook</label>
    <referenceTo>CPQ_Playbook__c</referenceTo>
    <relationshipLabel>CPQ System Settings</relationshipLabel>
    <relationshipName>CPQ_System_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_System_Settings__c/fields/Quote_Table_Actions__c.field-meta.xml
<CustomField>
    <fullName>Quote_Table_Actions__c</fullName>
    <description>Quote actions CPQ users have available</description>
    <inlineHelpText>Quote actions CPQ users have available</inlineHelpText>
    <label>Quote Table Actions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>View</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>Sync</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
                <label>Propsosal</label>
            </value>
            <value>
                <fullName>Clone</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_System_Settings__c/fields/Quote_Table_Columns__c.field-meta.xml
<CustomField>
    <fullName>Quote_Table_Columns__c</fullName>
    <description>Semicolon delineated list of field API names on the Quote object to be shown in the Quote Table view in CPQ. Any Quote Field API names are supported.</description>
    <inlineHelpText>Semicolon delineated list of field API names on the Quote object to be shown in the Quote Table view in CPQ. Any Quote Field API names are supported.</inlineHelpText>
    <label>Quote Table Columns</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/classes/cpq_ContractsByAccountTest.cls
/**
 * @author Tristan Moser
 * @date 4/19/2022
 *
 * @description Test class for cpq_AnyOppContainerClass class
 *
 */
@isTest
public class cpq_ContractsByAccountTest {

    /**
     * @description setup test data for use in test cases.
     **/
    @testSetup
    public static void setup() {

        // System Settings
        CPQ_System_Settings__c systemSettings = new CPQ_System_Settings__c(
            Contract_Table_Actions__c = 'View',
            Contract_Table_Columns__c = 'ContractNumber;Contract_Start_Date__c;Contract_Total__c;ContractTerm;isVoid__c',
            Default_Playbook__c = null,
            Quote_Table_Actions__c = 'View',
            Quote_Table_Columns__c = 'Name;Shell_Quote__c;Total_Price__c;End_Date__c;Discount'
        );
        insert systemSettings;

        // Pricebooks
        List<Pricebook2> testPricebooks = new List<Pricebook2>();
        testPricebooks.add(
            new Pricebook2(
                Id=Test.getStandardPricebookId(),
                Description = 'Standard Pricebook',
                IsActive = true
            )
        );
        update testPricebooks;

        // Playbooks
        List<CPQ_Playbook__c> testPlaybooks = new List<CPQ_Playbook__c>();
        testPlaybooks.add(
            new CPQ_Playbook__c(
                Default_Term_in_Months__c = 12,
                Entitlement_Summary_Columns__c = 'Quantity__c;End_Date__c',
                IsActive__c = true,
                Label__c = 'Playbook ' + 0,
                Name = 'Playbook ' + 0,
                Pricebook__c = testPricebooks[0].Id,
                Product_Summary_Columns__c = 'Quantity;End_Date',
                Proposal_Header__c = 'Header Text',
                Proposal_Header_Type__c = 'Text',
                Proposal_Footer__c = 'Footer Text'
            )
        );
        insert testPlaybooks;

        // Accounts
        List<Account> testAccounts = new List<Account>();
        testAccounts.add(
            new Account(
                Name = 'Test Account'
            )
        );
        testAccounts.add(
            new Account(
                Name = 'Account for testing'
            )
        );
        testAccounts.add(
            new Account(
                Name = 'Something to test'
            )
        );
        insert testAccounts;

        // Contracts
        List<Contract> testContracts = new List<Contract>();
        testContracts.add(
            new Contract(
                AccountId = testAccounts[0].Id
            )
        );
        testContracts.add(
            new Contract(
                AccountId = testAccounts[0].Id
            )
        );
        testContracts.add(
            new Contract(
                AccountId = testAccounts[1].Id
            )
        );
        testContracts.add(
            new Contract(
                AccountId = testAccounts[1].Id
            )
        );
        testContracts.add(
            new Contract(
                AccountId = testAccounts[2].Id
            )
        );
        testContracts.add(
            new Contract(
                AccountId = testAccounts[2].Id
            )
        );
        insert testContracts;
    }

    /**
     * @description Test to verify Account query is successful
     **/
    @isTest
    public static void testQueryAccount() {

        Account testAccount = [
            SELECT Id
            FROM Account
            LIMIT 1
        ];

        Test.startTest();

        cpq_ContractsByAccountClass.queryAccount(testAccount.Id);

        Test.stopTest();

        // Verify first in recently viewed
        List<Account> recentlyViewed = cpq_ContractsByAccountClass.getRecentlyViewed();
        System.assertEquals(testAccount.Id, recentlyViewed[0].Id);

    }

    /**
     * @description Test to verify AccountObj query is successful
     **/
    @isTest
    public static void testQueryAccountObj() {

        Account testAccount = [
            SELECT Id
            FROM Account
            LIMIT 1
        ];

        Test.startTest();

        cpq_ContractsByAccountClass.AccountObj acctObj = cpq_ContractsByAccountClass.queryAccountWithContracts(testAccount.Id);

        Test.stopTest();
    }

    /**
     * @description Test to verify sObject update is successful
     **/
    @isTest
    public static void testUpdateAccounts() {

        List<Account> testAccounts = [
            SELECT Id
            FROM Account
        ];
        for (Account acct : testAccounts) {
            acct.Type = 'Prospect';
        }

        Test.startTest();

        cpq_ContractsByAccountClass.updateRecords(testAccounts);

        Test.stopTest();

        // Verify updates
        List<Account> updatedAccounts = [
            SELECT Id,
                Type
            FROM Account
        ];
        for (Account acct : updatedAccounts) {
            System.assertEquals('Prospect', acct.Type);
        }

    }

}