SFDC_LD_Packages/CPQ/main/default/objects/Contract/fields/CPQ_Playbook__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Playbook used to configure contract</description>
    <label>CPQ Playbook</label>
    <referenceTo>CPQ_Playbook__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Contract_Entitlement__c/Contract_Entitlement__c.object-meta.xml
<CustomObject>
    <description>Entitlement line item for a given contract</description>
    <label>Contract Entitlement</label>
    <nameField>
        <label>Contract Entitlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/CPQ_Playbook__c.object-meta.xml
<CustomObject>
    <description>Set of deal questions for CPQ quote generation. Unique path for different opportunity types</description>
    <label>CPQ Playbook</label>
    <nameField>
        <label>CPQ Playbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Contract_View_Display_Fields__c.field-meta.xml
<CustomField>
    <fullName>Contract_View_Display_Fields__c</fullName>
    <description>List of Contract Field API names to be shown in CPQ when viewing a Contract records configuration.</description>
    <inlineHelpText>List of Contract Field API names to be shown in CPQ when viewing a Contract records configuration.</inlineHelpText>
    <label>Contract View Display Fields</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Entitlement_Summary_Columns__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Summary_Columns__c</fullName>
    <description>Semicolon delineated list of field API names on the Contract_Entitlement__c object to be shown in the Entitlement Summary view in CPQ. Any Contract_Entitlement__c Custom Field API names are supported.</description>
    <inlineHelpText>Semicolon delineated list of field API names on the Contract_Entitlement__c object to be shown in the Entitlement Summary view in CPQ. Any Contract_Entitlement__c Custom Field API names are supported.</inlineHelpText>
    <label>Entitlement Summary Columns</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Product_Summary_Columns__c.field-meta.xml
<CustomField>
    <fullName>Product_Summary_Columns__c</fullName>
    <description>Semicolon delineated list of attribute names on the Product level to be shown in the Product Summary view in CPQ. The following CPQ attributes are valid: &apos;Product_Name&apos;, &apos;Start_Date&apos;, &apos;End_Date&apos;, &apos;Quantity&apos;, &apos;Discount&apos;, &apos;Unit_Price&apos;, &apos;List_Price&apos;, &apos;Sub_Total_Price&apos;, and &apos;Total_Price&apos;. Any QuoteLineItem Field API names are also supported in the event that CPQ is custom stamping said fields.</description>
    <inlineHelpText>List of attribute names on the Product level to be shown in the Product Summary view in CPQ. The following CPQ attributes are valid: &apos;Product_Name&apos;, &apos;Start_Date&apos;, &apos;End_Date&apos;, &apos;Quantity&apos;, &apos;Discount&apos;, &apos;Unit_Price&apos;, &apos;List_Price&apos;, &apos;Sub_Total_Price&apos;, and &apos;Total_Price&apos;. Any QuoteLineItem Field API names are also supported in the event that CPQ is custom stamping said fields.</inlineHelpText>
    <label>Product Summary Columns</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Quote_View_Display_Fields__c.field-meta.xml
<CustomField>
    <fullName>Quote_View_Display_Fields__c</fullName>
    <description>List of Quote Field API names to be shown in CPQ when viewing a Quote records configuration. Sections can be created by inputting a label preceded by the '#' character (e.g. #Header). Blank spaces can be created by inputting a value that is not a valid field API name.</description>
    <inlineHelpText>List of Quote Field API names to be shown in CPQ when viewing a Quote records configuration. Sections can be created by inputting a label preceded by the '#' character (e.g. #Header). Blank spaces can be created by inputting a value that is not a valid field API name.</inlineHelpText>
    <label>Quote View Display Fields</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/CPQ_Playbook__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Playbook used to configure quote in CPQ</description>
    <label>CPQ Playbook</label>
    <referenceTo>CPQ_Playbook__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/classes/CPQ_Playbook_UpdatesUtil.cls
/**
* @author Tristan Moser
* @date 4/27/2022
*
* @description CPQ_Playbook__c object Updates class
*
* Tested by CPQ_Record_Validation_Test
*/
public with sharing class CPQ_Playbook_UpdatesUtil {

    /****************
     * MAIN METHODS
    ****************/

    /**
    * @description All same CPQ_Playbook__c updates that should run on Before Insert AND Before Update
    * @param playbooks CPQ_Playbook__c records with updated/inserted values in trigger context
    * @param oldPlaybooksMap Map - CPQ_Playbook__c Id to Old version of CPQ_Playbook__c
    */ 
    public static void samePlaybookBeforeUpdates(
        List<CPQ_Playbook__c> playbooks,
        Map<Id, CPQ_Playbook__c> oldPlaybooksMap
    ) {

        // Evaluate each CPQ_Playbook__c
        for (CPQ_Playbook__c playbook : playbooks) {

            CPQ_Playbook__c oldPlaybook = new CPQ_Playbook__c();
            // Not in Insert context
            if (playbook.Id != null) {
                oldPlaybook = oldPlaybooksMap.get(playbook.Id);
            }

            // Check for changes in fields that need validation

            // Product Summary Columns field change
            if (playbook.Product_Summary_Columns__c != oldPlaybook.Product_Summary_Columns__c &&
                playbook.Product_Summary_Columns__c != null
            ) {

                // Validate Product Summary Columns
                CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyFields(
                    playbook.Product_Summary_Columns__c.split(';'),
                    new List<String>{
                        'Product_Name',
                        'Start_Date',
                        'End_Date',
                        'Quantity',
                        'Discount',
                        'Unit_Price',
                        'List_Price',
                        'Sub_Total_Price',
                        'Total_Price'
                    },
                    'QuoteLineItem',
                    'Product Summary Columns'
                );
                if (results.result == false) {
                    playbook.addError(results.errorMessage);
                }
            }

            // Entitlement Summary Columns field change
            if (playbook.Entitlement_Summary_Columns__c != oldPlaybook.Entitlement_Summary_Columns__c &&
                playbook.Entitlement_Summary_Columns__c != null
            ) {

                // Validate Entitlement Summary Columns
                CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyFields(
                    playbook.Entitlement_Summary_Columns__c.split(';'),
                    new List<String>(),
                    'Contract_Entitlement__c',
                    'Contract Table Columns'
                );
                if (results.result == false) {
                    playbook.addError(results.errorMessage);
                }
            }

            // Quote View Display Fields field change
            if (playbook.Quote_View_Display_Fields__c != oldPlaybook.Quote_View_Display_Fields__c &&
                playbook.Quote_View_Display_Fields__c != null
            ) {

                // Validate Quote View Display Fields
                CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyFields(
                    playbook.Quote_View_Display_Fields__c.split(';'),
                    new List<String>(),
                    'Quote',
                    'Quote View Display Fields'
                );
                if (results.result == false) {
                    playbook.addError(results.errorMessage);
                }
            }

            // Contract View Display Fields field change
            if (playbook.Contract_View_Display_Fields__c != oldPlaybook.Contract_View_Display_Fields__c &&
                playbook.Contract_View_Display_Fields__c != null
            ) {

                // ValidateContract View Display Fields
                CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyFields(
                    playbook.Contract_View_Display_Fields__c.split(';'),
                    new List<String>(),
                    'Contract',
                    'Contract View Display Fields'
                );
                if (results.result == false) {
                    playbook.addError(results.errorMessage);
                }
            }
        }
    }
}