SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Answer__c/CPQ_Playbook_Answer__c.object-meta.xml
<CustomObject>
    <description>Child of Quote object. Houses responses/answers to a specific CPQ Playbook Question</description>
    <label>CPQ Playbook Answer</label>
    <nameField>
        <label>Playbook Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Answer__c/fields/CPQ_Playbook_Question__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook_Question__c</fullName>
    <description>CPQ Playbook Question the record answers</description>
    <label>CPQ Playbook Question</label>
    <referenceTo>CPQ_Playbook_Question__c</referenceTo>
    <relationshipLabel>CPQ Playbook Answers</relationshipLabel>
    <relationshipName>CPQ_Playbook_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Answer__c/fields/HasBeenTouched__c.field-meta.xml
<CustomField>
    <fullName>HasBeenTouched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the answer was &quot;touched&quot; in CPQ before the save</description>
    <label>HasBeenTouched</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Answer__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <description>Parent Quote record</description>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>CPQ Playbook Answers</relationshipLabel>
    <relationshipName>CPQ_Playbook_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approval__c/CPQ_Playbook_Approval__c.object-meta.xml
<CustomObject>
    <description>Approvals governing allowed behavior of CPQ Playbook modifications</description>
    <label>CPQ Playbook Approval</label>
    <nameField>
        <label>CPQ Playbook Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approval__c/fields/CPQ_Playbook__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook__c</fullName>
    <description>Playbook in which this approval is enforced</description>
    <inlineHelpText>Playbook in which this approval is enforced</inlineHelpText>
    <label>CPQ Playbook</label>
    <referenceTo>CPQ_Playbook__c</referenceTo>
    <relationshipLabel>CPQ Playbook Approvals</relationshipLabel>
    <relationshipName>CPQ_Playbook_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approval__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Reason users are shown for why this approval is being required</description>
    <inlineHelpText>Reason Users wee for why this approval is being required</inlineHelpText>
    <label>Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approval_Email_Section__c/CPQ_Playbook_Approval_Email_Section__c.object-meta.xml
<CustomObject>
    <description>Object to house section of Approval Email notification</description>
    <label>CPQ Playbook Approval Email Section</label>
    <nameField>
        <label>Approval Email Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Approval Email Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approval_Email_Section__c/fields/CPQ_Playbook_Approval__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook_Approval__c</fullName>
    <description>CPQ Playbook Approval in which the Email Section is used</description>
    <inlineHelpText>Playbook Approval in which the email section is used</inlineHelpText>
    <label>CPQ Playbook Approval</label>
    <referenceTo>CPQ_Playbook_Approval__c</referenceTo>
    <relationshipLabel>CPQ Playbook Approval Email Sections</relationshipLabel>
    <relationshipName>CPQ_Playbook_Approval_Email_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/CPQ_Playbook_Question__c.object-meta.xml
<CustomObject>
    <description>Specific deal question for CPQ quote generation</description>
    <label>CPQ Playbook Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/fields/Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>Answer_Type__c</fullName>
    <description>Type of field where the user will place the question&apos;s answer</description>
    <inlineHelpText>Type of field where Users will place the question&apos;s answer</inlineHelpText>
    <label>Answer Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Multi-Select Picklist</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/fields/Proposal_Label__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Label__c</fullName>
    <description>Displayed label in Proposal if used in an Answer Table</description>
    <inlineHelpText>Displayed label Users see in Proposal if used in an Answer Table</inlineHelpText>
    <label>Proposal Label</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/fields/Variable_Name__c.field-meta.xml
<CustomField>
    <fullName>Variable_Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Variable Name used to identify piped text in Proposal PDF</description>
    <inlineHelpText>Unique Variable Name used to identify piped text in Proposal PDF</inlineHelpText>
    <label>Variable Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Quote_Approval_Step__c/CPQ_Quote_Approval_Step__c.object-meta.xml
<CustomObject>
    <description>Quote level approval step for CPQ Playbook Approvals. Matches up to CPQ Playbook Approval Groups</description>
    <label>CPQ Quote Approval Step</label>
    <nameField>
        <label>CPQ Quote Approval Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Quote Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Quote_Approval_Step__c/fields/CPQ_Quote_Approval__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Quote_Approval__c</fullName>
    <description>Approval for which record is a step</description>
    <label>CPQ Quote Approval</label>
    <referenceTo>CPQ_Quote_Approval__c</referenceTo>
    <relationshipLabel>CPQ Quote Approval Steps</relationshipLabel>
    <relationshipName>CPQ_Quote_Approval_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Quote_Approver__c/CPQ_Quote_Approver__c.object-meta.xml
<CustomObject>
    <description>Quote level approver for CPQ Playbook Approvals. Matches up to CPQ Playbook Approver</description>
    <label>CPQ Quote Approver</label>
    <nameField>
        <label>Quote Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Quote Approvers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Quote_Approver__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>CPQ_Quote_Approval_Step__r.CPQ_Quote_Approval__r.Quote__r.Opportunity.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Quote_Approver__c/fields/Approval__c.field-meta.xml
<CustomField>
    <fullName>Approval__c</fullName>
    <formula>CPQ_Quote_Approval_Step__r.CPQ_Quote_Approval__r.CPQ_Playbook_Approval__r.Label__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approval</label>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Quote_Approver__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Approver that needs to approve this approver record</description>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CPQ_Quote_Approvers</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Quote_Approver__c/fields/CPQ_Quote_Approval_Step__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Quote_Approval_Step__c</fullName>
    <description>Approval step for which record is an approver</description>
    <label>CPQ Quote Approval Step</label>
    <referenceTo>CPQ_Quote_Approval_Step__c</referenceTo>
    <relationshipLabel>CPQ Quote Approvers</relationshipLabel>
    <relationshipName>CPQ_Quote_Approvers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Quote_Approver__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>CPQ_Quote_Approval_Step__r.CPQ_Quote_Approval__r.Quote__r.Opportunity.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Quote_Approver__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <formula>CPQ_Quote_Approval_Step__r.CPQ_Quote_Approval__r.Quote__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote</label>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/Adjustment_of_Contract__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_of_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract of which quote is an adjustment</description>
    <label>Adjustment of Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Quote Adjustments</relationshipLabel>
    <relationshipName>Quote_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/Adjustment_Type__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Type__c</fullName>
    <description>Type of Contract Adjustment the Quote outlines</description>
    <inlineHelpText></inlineHelpText>
    <label>Adjustment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/CPQ_Playbook__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Playbook used to configure quote in CPQ</description>
    <label>CPQ Playbook</label>
    <referenceTo>CPQ_Playbook__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Latest end date of Quote Line Items</description>
    <label>End Date</label>
    <summarizedField>QuoteLineItem.End_Date__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Earliest start date of Quote Line Items</description>
    <label>Start Date</label>
    <summarizedField>QuoteLineItem.Start_Date__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/SubTotal_Price__c.field-meta.xml
<CustomField>
    <fullName>SubTotal_Price__c</fullName>
    <description>Price before any price adjustments</description>
    <label>SubTotal Price</label>
    <summarizedField>QuoteLineItem.SubTotal_Price__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>QuoteLineItem.Total_Price__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/classes/cpq_ApprovalDisplayController.cls
public with sharing class cpq_ApprovalDisplayController {

    public CPQ_Quote_Approver__c approverRecord;
    public List<sectionObj> sections;

    public void setApproverRecord(CPQ_Quote_Approver__c record) {
        Id recordId = record.Id;
        approverRecord = [
            SELECT Id,
                Approval__c,
                CreatedBy.Name,
                CPQ_Quote_Approval_Step__r.CPQ_Quote_Approval__r.CPQ_Playbook_Approval__r.Reason__c,
                Quote__c,
                CPQ_Quote_Approval_Step__r.CPQ_Quote_Approval__r.Quote__r.OpportunityId,
                Opportunity__c,
                CPQ_Quote_Approval_Step__r.CPQ_Quote_Approval__r.Quote__r.Opportunity.AccountId,
                Account__c
            FROM CPQ_Quote_Approver__c
            WHERE Id=:recordId
        ];
    }

    public CPQ_Quote_Approver__c getApproverRecord() {
        return approverRecord;
    }

    public void setSections (List<sectionObj> s) {
        sections = s;
    }
        
    public List<sectionObj> getSections() {

        /****************
         * RECORD PREP
        ****************/

        Id approverId = approverRecord.Id;

        // Approver Info
        CPQ_Quote_Approver__c approverInfo = [
            SELECT Id,
                Approver__r.Id,
                Approver__r.Name,
                CPQ_Quote_Approval_Step__r.CPQ_Quote_Approval__r.CPQ_Playbook_Approval__c,
                CPQ_Quote_Approval_Step__r.CPQ_Quote_Approval__r.Quote__c
            FROM CPQ_Quote_Approver__c
            WHERE Id=:approverId
        ];
        Id quoteId = approverInfo.CPQ_Quote_Approval_Step__r.CPQ_Quote_Approval__r.Quote__c;
        Id approvalId = approverInfo.CPQ_Quote_Approval_Step__r.CPQ_Quote_Approval__r.CPQ_Playbook_Approval__c;

        // Quote Info
        String quoteQuery = ''
            + 'SELECT Id,'
                + 'Adjustment_of_Contract__c,'
                + 'Adjustment_Type__c,'
                + 'CPQ_Playbook__c,'
                + (System.UserInfo.isMultiCurrencyOrganization() == true ? 'CurrencyIsoCode,' : '')
                + 'End_Date__c,'
                + 'Start_Date__c,'
                + 'SubTotal_Price__c,'
                + 'Total_Price__c'
            + ' FROM Quote'
            + ' WHERE Id=:quoteId';
        Quote quoteInfo = Database.query(quoteQuery);

        // Currency Iso Code
        String currencyIsoCode;
        if (System.UserInfo.isMultiCurrencyOrganization() == true) {
            currencyIsoCode = (String) quoteInfo.get('CurrencyIsoCode');
        } else {
            currencyIsoCode = System.UserInfo.getDefaultCurrency();
        }

        // Currency Symbol
        String currencySymbol = currencyIsoCode;
        Map<String, String> currencySymbolsByIsoCode = new Map<String, String>{
            'AUD' => 'A$',
            'AWG' => 'ƒ',
            'BDT' => '৳',
            'CAD' => 'CAD$',
            'CNY' => '¥',
            'CRC' => '₡',
            'DKK' => 'kr',
            'EGP' => '£',
            'EUR' => '€',
            'FKP' => '£',
            'GBP' => '£',
            'GIP' => '£',
            'ILS' => '₪',
            'INR' => '₹',
            'ISK' => 'kr',
            'JPY' => '¥',
            'KHR' => '៛',
            'KRW' => '₩',
            'KZT' => '₸',
            'LBP' => '£',
            'NGN' => '₦',
            'NOK' => 'kr',
            'PHP' => '₱',
            'PYG' => '₲',
            'RUB' => '₽',
            'SDG' => '£',
            'SEK' => 'kr',
            'SHP' => '£',
            'SYP' => '£',
            'TRY' => '₺',
            'USD' => '$'
        };
        if (currencySymbolsByIsoCode.containsKey(currencyIsoCode)) {
            currencySymbol = currencySymbolsByIsoCode.get(currencyIsoCode);
        }

        // Sections that meet critieria
        List<sectionObj> tempSections = new List<sectionObj>();

        // Question to Quote Answer Map
        Map<String, CPQ_Playbook_Answer__c> answerMap = new Map<String, CPQ_Playbook_Answer__c>();
        for (CPQ_Playbook_Answer__c answer : [
            SELECT Id,
                CPQ_Playbook_Question__c,
                CPQ_Playbook_Question__r.Answer_Type__c,
                CPQ_Playbook_Question__r.Proposal_Label__c,
                CPQ_Playbook_Question__r.Variable_Name__c,
                HasBeenTouched__c,
                Quote__c,
                Value_Boolean__c,
                Value_Currency__c,
                Value_Date__c,
                Value_Decimal__c,
                Value_Integer__c,
                Value_Text__c
            FROM CPQ_Playbook_Answer__c
            WHERE Quote__c=:quoteInfo.Id
        ]) {
            answerMap.put(answer.CPQ_Playbook_Question__r.Variable_Name__c, answer);
        }

        // All possible sections for playbook
        List<CPQ_Playbook_Approval_Email_Section__c> allSections = new List<CPQ_Playbook_Approval_Email_Section__c>();
        Set<Id> contentDocumentIDs = new Set<Id>();
        for (CPQ_Playbook_Approval_Email_Section__c section : [
            SELECT Id,
                Answer_Table_Questions__c,
                Body_Text_Block_1__c,
                Body_Text_Block_2__c,
                Body_Text_Block_3__c,
                CPQ_Playbook_Approval__c,
                IsActive__c,
                Name,
                Record_Table_Query__c,
                Section_Type__c,
                Table_Entries_Font_Color__c,
                Table_Entries_Font_Size__c,
                Table_Headers_Font_Color__c,
                Table_Headers_Font_Size__c,
                (
                    SELECT Id,
                        ContentDocument.Id
                    FROM AttachedContentDocuments
                )
            FROM CPQ_Playbook_Approval_Email_Section__c
            WHERE CPQ_Playbook_Approval__c=:approvalId AND
                IsActive__c = true
            ORDER BY Display_Order__c ASC
        ]) {
            allSections.add(section);

            if (section.AttachedContentDocuments.size() > 0) {
                contentDocumentIDs.add(section.AttachedContentDocuments[0].ContentDocument.Id);
            }
        }

        // Get ContentDistributions
        Map<Id, String> imageLinks = new Map<Id, String>();
        if (contentDocumentIDs.size() > 0) {

            // Map existing distribution links by file
            for (ContentDistribution dist : [
                SELECT Id,
                    ContentDocumentId,
                    ContentDownloadUrl
                FROM ContentDistribution
                WHERE ContentDocumentId IN:contentDocumentIDs
            ]) {
                imageLinks.put(dist.ContentDocumentId, dist.ContentDownloadUrl);
            }
        }


        /****************
         * SECTION PREP
        ****************/


        // Prepare each section
        for (CPQ_Playbook_Approval_Email_Section__c section : allSections) {

            // Pipe text if applicable
            for (String questionVar : answerMap.keySet()) {

                CPQ_Playbook_Answer__c answer = answerMap.get(questionVar);
                if (answer != null) {
                    // Text 1
                    if (section.Body_Text_Block_1__c != null) {
                        if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Boolean') {
                            section.Body_Text_Block_1__c = section.Body_Text_Block_1__c.replace('{%'+questionVar+'%}',String.valueOf(answer.Value_Boolean__c));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Currency') {
                            section.Body_Text_Block_1__c = section.Body_Text_Block_1__c.replace('{%'+questionVar+'%}',currencySymbol + String.valueOf(answer.Value_Currency__c != null ? answer.Value_Currency__c.format() : ''));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Date') {
                            section.Body_Text_Block_1__c = section.Body_Text_Block_1__c.replace('{%'+questionVar+'%}',String.valueOf(answer.Value_Date__c != null ? answer.Value_Date__c.format() : ''));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Decimal') {
                            section.Body_Text_Block_1__c = section.Body_Text_Block_1__c.replace('{%'+questionVar+'%}',String.valueOf(answer.Value_Decimal__c != null ? answer.Value_Decimal__c.format() : ''));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Integer') {
                            section.Body_Text_Block_1__c = section.Body_Text_Block_1__c.replace('{%'+questionVar+'%}',String.valueOf(answer.Value_Integer__c != null ? answer.Value_Integer__c.format() : ''));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Picklist' ||
                            answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Multi-Select Picklist' ||
                            answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Text' ||
                            answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Text Area'
                        ) {
                            section.Body_Text_Block_1__c = section.Body_Text_Block_1__c.replace('{%'+questionVar+'%}',answer.Value_Text__c != null ? answer.Value_Text__c : '');
                        } 
                    }
                    // Text 2
                    if (section.Body_Text_Block_2__c != null) {
                        if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Boolean') {
                            section.Body_Text_Block_2__c = section.Body_Text_Block_2__c.replace('{%'+questionVar+'%}',String.valueOf(answer.Value_Boolean__c));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Currency') {
                            section.Body_Text_Block_2__c = section.Body_Text_Block_2__c.replace('{%'+questionVar+'%}',currencySymbol + String.valueOf(answer.Value_Currency__c != null ? answer.Value_Currency__c.format() : ''));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Date') {
                            section.Body_Text_Block_2__c = section.Body_Text_Block_2__c.replace('{%'+questionVar+'%}',String.valueOf(answer.Value_Date__c != null ? answer.Value_Date__c.format() : ''));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Decimal') {
                            section.Body_Text_Block_2__c = section.Body_Text_Block_2__c.replace('{%'+questionVar+'%}',String.valueOf(answer.Value_Decimal__c != null ? answer.Value_Decimal__c.format() : ''));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Integer') {
                            section.Body_Text_Block_2__c = section.Body_Text_Block_2__c.replace('{%'+questionVar+'%}',String.valueOf(answer.Value_Integer__c != null ? answer.Value_Integer__c.format() : ''));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Picklist' ||
                            answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Multi-Select Picklist' ||
                            answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Text' ||
                            answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Text Area'
                        ) {
                            section.Body_Text_Block_2__c = section.Body_Text_Block_2__c.replace('{%'+questionVar+'%}',answer.Value_Text__c != null ? answer.Value_Text__c : '');
                        } 
                    }
                    // Text 3
                    if (section.Body_Text_Block_3__c != null) {
                        if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Boolean') {
                            section.Body_Text_Block_3__c = section.Body_Text_Block_3__c.replace('{%'+questionVar+'%}',String.valueOf(answer.Value_Boolean__c));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Currency') {
                            section.Body_Text_Block_3__c = section.Body_Text_Block_3__c.replace('{%'+questionVar+'%}',currencySymbol + String.valueOf(answer.Value_Currency__c != null ? answer.Value_Currency__c.format() : ''));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Date') {
                            section.Body_Text_Block_3__c = section.Body_Text_Block_3__c.replace('{%'+questionVar+'%}',String.valueOf(answer.Value_Date__c != null ? answer.Value_Date__c.format() : ''));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Decimal') {
                            section.Body_Text_Block_3__c = section.Body_Text_Block_3__c.replace('{%'+questionVar+'%}',String.valueOf(answer.Value_Decimal__c != null ? answer.Value_Decimal__c.format() : ''));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Integer') {
                            section.Body_Text_Block_3__c = section.Body_Text_Block_3__c.replace('{%'+questionVar+'%}',String.valueOf(answer.Value_Integer__c != null ? answer.Value_Integer__c.format() : ''));
                        }
                        else if (answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Picklist' ||
                            answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Multi-Select Picklist' ||
                            answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Text' ||
                            answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Text Area'
                        ) {
                            section.Body_Text_Block_3__c = section.Body_Text_Block_3__c.replace('{%'+questionVar+'%}',answer.Value_Text__c != null ? answer.Value_Text__c : '');
                        } 
                    }
                }
            }

            // Remaining Question / EOL Text wrap / Empty Span resolution
            String remainingQuestionRegex = '\\{%[^%\\}]*%\\}';
            String emptySpanRegex = '<span[^>]*></span>';
            if (section.Body_Text_Block_1__c != null) {
                section.Body_Text_Block_1__c = section.Body_Text_Block_1__c.replace('{%Approver.Name%}', approverInfo.Approver__r.Name);
                section.Body_Text_Block_1__c = section.Body_Text_Block_1__c.replaceAll(remainingQuestionRegex, '');
                section.Body_Text_Block_1__c = section.Body_Text_Block_1__c.replace('</p>', ' <span style="font-size:0.1px;color:white">|</span></p>');
                section.Body_Text_Block_1__c = section.Body_Text_Block_1__c.replaceAll(emptySpanRegex, '');
            }
            if (section.Body_Text_Block_2__c != null) {
                section.Body_Text_Block_2__c = section.Body_Text_Block_2__c.replace('{%Approver.Name%}', approverInfo.Approver__r.Name);
                section.Body_Text_Block_2__c = section.Body_Text_Block_2__c.replaceAll(remainingQuestionRegex, '');
                section.Body_Text_Block_2__c = section.Body_Text_Block_2__c.replace('</p>', ' <span style="font-size:0.1px;color:white">|</span></p>');
                section.Body_Text_Block_2__c = section.Body_Text_Block_2__c.replaceAll(emptySpanRegex, '');
            }
            if (section.Body_Text_Block_3__c != null) {
                section.Body_Text_Block_3__c = section.Body_Text_Block_3__c.replace('{%Approver.Name%}', approverInfo.Approver__r.Name);
                section.Body_Text_Block_3__c = section.Body_Text_Block_3__c.replaceAll(remainingQuestionRegex, '');
                section.Body_Text_Block_3__c = section.Body_Text_Block_3__c.replace('</p>', ' <span style="font-size:0.1px;color:white">|</span></p>');
                section.Body_Text_Block_3__c = section.Body_Text_Block_3__c.replaceAll(emptySpanRegex, '');
            }

            // Prep section object
            sectionObj sectionToAdd = new sectionObj();
            sectionToAdd.section = section;
            if (section.AttachedContentDocuments.size() > 0) {
                sectionToAdd.imageId = imageLinks.get(section.AttachedContentDocuments[0].ContentDocument.Id);
            }

            // Configure Record Table
            if (section.Section_Type__c == 'Record Table') {

                // Get Object Name and Fields from Query String
                String objName = section.Record_Table_Query__c.toLowerCase().split('from')[1].split(' ')[1];
                List<String> objFields = section.Record_Table_Query__c.toLowerCase().split(' from')[0].split('select ')[1].split(',');

                // Describe Object
                SObjectType objType = ((SObject)(Type.forName('Schema.' + objName).newInstance())).getSObjectType();
                DescribeSObjectResult obj = objType.getDescribe();

                // Get Headers from Records fields
                sectionToAdd.tableHeaders = new List<String>();
                for (String field : objFields) {
                    sectionToAdd.tableHeaders.add(
                        obj.fields
                            .getMap()
                            .get(field)
                            .getDescribe()
                            .getLabel()
                    );
                }

                // Get String values of record values
                sectionToAdd.tableRecords = new List<List<String>>();
                for (sObject rec : Database.query(section.Record_Table_Query__c)) {
                    List<String> record = new List<String>();
                    for (String field : objFields) {
                        Schema.DisplayType fieldType = obj.fields
                            .getMap()
                            .get(field)
                            .getDescribe()
                            .getType();
                        if (new List<Schema.DisplayType>{Schema.DisplayType.Currency,Schema.DisplayType.Double,Schema.DisplayType.Integer,Schema.DisplayType.Date}.contains(
                            fieldType
                        )) {
                            String val = '';
                            
                            if (fieldType == Schema.DisplayType.Double) {
                                Double decVal = (Double)rec.get(field);
                                if (decVal != null) {
                                    val = String.valueOf(decVal.format());
                                }
                            }
                            else if (fieldType == Schema.DisplayType.Currency) {
                                Decimal decVal = (Decimal)rec.get(field);
                                if (decVal != null) {
                                    val = currencySymbol + String.valueOf(decVal.format());
                                }
                            }
                            else if (fieldType == Schema.DisplayType.Integer) {
                                Integer intVal = (Integer)rec.get(field);
                                if (intVal != null) {
                                    val = String.valueOf(intVal.format());
                                }
                            }
                            else if (fieldType == Schema.DisplayType.Date) {
                                Date dateVal = (Date)rec.get(field);
                                if (dateVal != null) {
                                    val = String.valueOf(dateVal.format());
                                }
                            }

                            record.add(val);
                        } else {
                            String val = String.valueOf(rec.get(field));
                            record.add(val);
                        }
                    }
                    sectionToAdd.tableRecords.add(record);
                }
            }

            // Configure Answer Table
            if (section.Section_Type__c.contains('Answer Table')) {
                // Get Answer Pair Sets from Question Labels
                sectionToAdd.answerTablePairSets = new List<List<AnswerPair>>();
                List<AnswerPair> currAnswerPairSet = new List<AnswerPair>();
                if (section.Answer_Table_Questions__c != null) {
                    for (String questionVar : section.Answer_Table_Questions__c.split(';')) {

                        // Associated Answer
                        CPQ_Playbook_Answer__c answer = answerMap.get(questionVar);
                        AnswerPair ansPair = new AnswerPair();
                        ansPair.label = '';
                        ansPair.value = '';

                        if (answer != null) {

                            // Label
                            ansPair.label = answer.CPQ_Playbook_Question__r.Proposal_Label__c;

                            // Value
                            if (
                                answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Boolean' &&
                                answer.Value_Boolean__c != null
                            ) {
                                ansPair.value = String.valueOf(answer.Value_Boolean__c);
                            }
                            else if (
                                answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Currency' &&
                                answer.Value_Currency__c != null
                            ) {
                                ansPair.value = String.valueOf(answer.Value_Currency__c.format());
                            }
                            else if (
                                answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Date' &&
                                answer.Value_Date__c != null    
                            ) {
                                ansPair.value = String.valueOf(answer.Value_Date__c.format());
                            }
                            else if (
                                answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Decimal' &&
                                answer.Value_Decimal__c != null    
                            ) {
                                ansPair.value = String.valueOf(answer.Value_Decimal__c.format());
                            }
                            else if (
                                answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Integer' &&
                                answer.Value_Integer__c != null
                            ) {
                                ansPair.value = String.valueOf(answer.Value_Integer__c.format());
                            }
                            else if (
                                (
                                    answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Picklist' ||
                                    answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Multi-Select Picklist' ||
                                    answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Text' ||
                                    answer.CPQ_Playbook_Question__r.Answer_Type__c == 'Text Area'
                                ) &&
                                answer.Value_Text__c != null
                            ) {
                                ansPair.value = answer.Value_Text__c;
                            }
                        }

                        currAnswerPairSet.add(ansPair);

                        if (section.Section_Type__c == 'Answer Table - 1 column' ||
                            (
                                section.Section_Type__c == 'Answer Table - 2 columns' &&
                                currAnswerPairSet.size() == 2
                            )
                        ) {
                            sectionToAdd.answerTablePairSets.add(currAnswerPairSet);
                            currAnswerPairSet = new List<AnswerPair>();
                        }
                    }
                }

                if (currAnswerPairSet.size() > 0) {
                    sectionToAdd.answerTablePairSets.add(currAnswerPairSet);
                }
            }

            tempSections.add(sectionToAdd);
            
        }

        return tempSections;
    } 

    public class sectionObj {
        public CPQ_Playbook_Approval_Email_Section__c section {get; set;}
        public String imageID {get; set;}
        public List<String> tableHeaders {get; set;}
        public List<List<String>> tableRecords {get; set;}
        public List<List<AnswerPair>> answerTablePairSets {get; set;}
    }

    public class AnswerPair {
        public String label {get; set;}
        public String value {get; set;}
    }
}