SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Proposal_Section__c/CPQ_Playbook_Proposal_Section__c.object-meta.xml
<CustomObject>
    <description>Section Blueprint for Proposal PDF on a given CPQ Playbook</description>
    <label>CPQ Playbook Proposal Section</label>
    <nameField>
        <label>CPQ Playbook Proposal Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Proposal Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Proposal_Section__c/fields/Record_Table_Query__c.field-meta.xml
<CustomField>
    <fullName>Record_Table_Query__c</fullName>
    <description>SOQL query for records to be shown in the table. The only allowed binded variable is 'quoteRecordId' (e.g. WHERE QuoteId=:quoteRecordId). Do NOT include spaces between field API names (e.g. SELECT Id,Test__c)</description>
    <inlineHelpText>SOQL query for records to be shown in the table. The only allowed binded variable is 'quoteRecordId' (e.g. WHERE QuoteId=:quoteRecordId). Do NOT include spaces between field API names (e.g. SELECT Id,Test__c)</inlineHelpText>
    <label>Record Table Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/classes/CPQ_Proposal_Section_UpdatesUtil.cls
/**
* @author Tristan Moser
* @date 4/27/2022
*
* @description CPQ_Playbook_Proposal_Section__c object Updates class
*
* Tested by CPQ_Record_Validation_Test
*/
public with sharing class CPQ_Proposal_Section_UpdatesUtil {

    /****************
     * MAIN METHODS
    ****************/

    /**
    * @description All same CPQ_Playbook_Proposal_Section__c updates that should run on Before Insert AND Before Update
    * @param sections CPQ_Playbook_Proposal_Section__c records with updated/inserted values in trigger context
    * @param oldSectionsMap Map - CPQ_Playbook_Proposal_Section__c Id to Old version of CPQ_Playbook_Proposal_Section__c
    */ 
    public static void sameSectionBeforeUpdates(
        List<CPQ_Playbook_Proposal_Section__c> sections,
        Map<Id, CPQ_Playbook_Proposal_Section__c> oldSectionsMap
    ) {

        // Evaluate each CPQ_Playbook_Proposal_Section__c
        for (CPQ_Playbook_Proposal_Section__c section : sections) {

            CPQ_Playbook_Proposal_Section__c oldSection = new CPQ_Playbook_Proposal_Section__c();
            // Not in Insert context
            if (section.Id != null) {
                oldSection = oldSectionsMap.get(section.Id);
            }

            // Check for changes in fields that need validation

            // Record Tabl Query field change
            if (section.Record_Table_Query__c != oldSection.Record_Table_Query__c&&
                section.Record_Table_Query__c != null
            ) {

                // Only allowed binded variable: quoteRecordId
                String queryToValidate = section.Record_Table_Query__c.replace(':quoteRecordId', '\'\'');

                // Validate Query String field
                CPQ_Record_Validation.ResultClass queryResults = CPQ_Record_Validation.verifyQuery(
                    queryToValidate,
                    'Record Table Query'
                );
                if (queryResults.result == false) {
                    section.addError(queryResults.errorMessage);
                }
            }
        }
    }
}