SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Action__c/CPQ_Playbook_Rule_Action__c.object-meta.xml
<CustomObject>
    <description>Action to be run upon successful Rule evaluation</description>
    <label>CPQ Playbook Rule Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Rule_Action__c/fields/Product_Adjustment_Field__c.field-meta.xml
<CustomField>
    <fullName>Product_Adjustment_Field__c</fullName>
    <description>Field on product that should be adjusted. Valid options include &apos;Quantity&apos;, &apos;Unit_Price&apos;, &apos;List_Price&apos;, &apos;Start_Date&apos;, &apos;End_Date&apos;, &apos;Quantity_Editable&apos;, &apos;Dates_Editable&apos;, &apos;Discountable&apos;, &apos;List_Price_Editable&apos;, &apos;Manually_Addible&apos;, and &apos;Removable&apos; for CPQ value adjustments. Alternatively, any QuoteLineItem field API name can be placed here and it will be saved to the product&apos;s QuoteLineItem record upon CPQ save.</description>
    <inlineHelpText>Field on product that should be adjusted. Valid options include &apos;Quantity&apos;, &apos;Unit_Price&apos;, &apos;List_Price&apos;, &apos;Start_Date&apos;, &apos;End_Date&apos;, &apos;Quantity_Editable&apos;, &apos;Dates_Editable&apos;, &apos;Discountable&apos;, &apos;List_Price_Editable&apos;, &apos;Manually_Addible&apos;, and &apos;Removable&apos; for CPQ value adjustments. Alternatively, any QuoteLineItem field API name can be placed here and it will be saved to the product&apos;s QuoteLineItem record upon CPQ save.</inlineHelpText>
    <label>Product Adjustment Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/QuoteLineItem/fields/CPQ_Playbook_Rule_Action__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook_Rule_Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Action that added this QLI in CPQ</description>
    <label>CPQ Playbook Rule Action</label>
    <referenceTo>CPQ_Playbook_Rule_Action__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/classes/CPQ_Rule_Action_UpdatesUtil.cls
/**
* @author Tristan Moser
* @date 4/27/2022
*
* @description CPQ_Playbook_Rule_Action__c object Updates class
*
* Tested by CPQ_Record_Validation_Test
*/
public with sharing class CPQ_Rule_Action_UpdatesUtil {

    /****************
     * MAIN METHODS
    ****************/

    /**
    * @description All same CPQ_Playbook_Rule_Action__c updates that should run on Before Insert AND Before Update
    * @param actions CPQ_Playbook_Rule_Action__c records with updated/inserted values in trigger context
    * @param oldActionsMap Map - CPQ_Playbook_Rule_Action__c Id to Old version of CPQ_Playbook_Rule_Action__c
    */ 
    public static void sameActionBeforeUpdates(
        List<CPQ_Playbook_Rule_Action__c> actions,
        Map<Id, CPQ_Playbook_Rule_Action__c> oldActionsMap
    ) {

        // Evaluate each CPQ_Playbook_Rule_Action__c
        for (CPQ_Playbook_Rule_Action__c action : actions) {

            CPQ_Playbook_Rule_Action__c oldAction = new CPQ_Playbook_Rule_Action__c();
            // Not in Insert context
            if (action.Id != null) {
                oldAction = oldActionsMap.get(action.Id);
            }

            // Check for changes in fields that need validation

            // Product Adjustment Field field change
            if (
                action.Product_Adjustment_Field__c != oldAction.Product_Adjustment_Field__c &&
                action.Product_Adjustment_Field__c != null
            ) {

                // Validate Product Field field
                CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyFields(
                    new List<String>{action.Product_Adjustment_Field__c},
                    new List<String>{
                        'Start_Date',
                        'End_Date',
                        'Quantity',
                        'Discount',
                        'Unit_Price',
                        'List_Price',
                        'Quantity_Editable',
                        'Dates_Editable',
                        'Discountable',
                        'List_Price_Editable',
                        'Manually_Addible',
                        'Removable'
                    },
                    'QuoteLineItem',
                    'Product Adjustment Field'
                );
                if (results.result == false) {
                    action.addError(results.errorMessage);
                }
            }
        }
    }
}