SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/CPQ_Playbook_Question__c.object-meta.xml
<CustomObject>
    <description>Specific deal question for CPQ quote generation</description>
    <label>CPQ Playbook Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/fields/Default_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Field_Value__c</fullName>
    <description>Field from CPQ data object to use for default value for answer</description>
    <inlineHelpText>Field from CPQ data objects to use for default value for answer. Valid objects include: &apos;Account&apos;, &apos;Opportunity&apos;, &apos;Quote&apos;, &apos;Profile&apos;, &apos;UserRole&apos;, and &apos;User&apos;</inlineHelpText>
    <label>Default Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/fields/Query_String__c.field-meta.xml
<CustomField>
    <fullName>Query_String__c</fullName>
    <description>Query string used to query records. This should NOT include any binded variables. Any dynamic alterations to this query should be handled in a CPQ Rule.</description>
    <inlineHelpText>Query string used to query records. This should NOT include any binded variables. Any dynamic alterations to this query should be handled in a CPQ Rule. Ensure all fields from the Record Display Fields field are also included here.</inlineHelpText>
    <label>Query String</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/fields/Quote_Save_Field__c.field-meta.xml
<CustomField>
    <fullName>Quote_Save_Field__c</fullName>
    <description>Quote Field API name where question&apos;s answer should be placed</description>
    <inlineHelpText>If populated, the question&apos;s answer will be populated in this Quote field. Only the Quote field API name should be placed in this field</inlineHelpText>
    <label>Quote Save Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Question__c/fields/Record_Display_Fields__c.field-meta.xml
<CustomField>
    <fullName>Record_Display_Fields__c</fullName>
    <description>Semi-colon delineated list of Field API names when Answer Type is Record Lookup</description>
    <inlineHelpText>List of Field API names to display for each queried record. Ensure that all fields listed here are also included in the Query String.</inlineHelpText>
    <label>Record Display Fields</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/classes/CPQ_Playbook_Question_UpdatesUtil.cls
/**
* @author Tristan Moser
* @date 4/27/2022
*
* @description CPQ_Playbook_Question__c object Updates class
*
* Tested by CPQ_Record_Validation_Test
*/
public with sharing class CPQ_Playbook_Question_UpdatesUtil {

    /****************
     * MAIN METHODS
    ****************/

    /**
    * @description All same CPQ_Playbook_Question__c updates that should run on Before Insert AND Before Update
    * @param questions CPQ_Playbook_Question__c records with updated/inserted values in trigger context
    * @param oldQuestionsMap Map - CPQ_Playbook_Question__c Id to Old version of CPQ_Playbook_Question__c
    */ 
    public static void sameQuestionBeforeUpdates(
        List<CPQ_Playbook_Question__c> questions,
        Map<Id, CPQ_Playbook_Question__c> oldQuestionsMap
    ) {

        // Evaluate each CPQ_Playbook_Question__c
        for (CPQ_Playbook_Question__c question : questions) {

            CPQ_Playbook_Question__c oldQuestion = new CPQ_Playbook_Question__c();
            // Not in Insert context
            if (question.Id != null) {
                oldQuestion = oldQuestionsMap.get(question.Id);
            }

            // Check for changes in fields that need validation

            // Query String or Record Display Fields change
            if (
                (
                    question.Record_Display_Fields__c != oldQuestion.Record_Display_Fields__c ||
                    question.Query_String__c != oldQuestion.Query_String__c
                 ) &&
                question.Query_String__c != null &&
                question.Record_Display_Fields__c != null
            ) {


                // Validate Query String field
                CPQ_Record_Validation.ResultClass queryResults = CPQ_Record_Validation.verifyQuery(
                    question.Query_String__c,
                    'Query String'
                );
                if (queryResults.result == false) {
                    question.addError(queryResults.errorMessage);
                }

                // Valid Query
                else {
                    // Extract Object name from query string
                    String objectName = question.Query_String__c.toLowerCase().split('from')[1].split(' ')[1];

                    // Validate Record Display Fields field
                    CPQ_Record_Validation.ResultClass displayResults = CPQ_Record_Validation.verifyFields(
                        question.Record_Display_Fields__c.split(';'),
                        new List<String>(),
                        objectName,
                        'Record Display Fields'
                    );
                    if (displayResults.result == false) {
                        question.addError(displayResults.errorMessage);
                    }
                }
            }

            // Quote Save Field change
            if (question.Quote_Save_Field__c != oldQuestion.Quote_Save_Field__c &&
                question.Quote_Save_Field__c != null
            ) {

                // Validate Quote Save Field field
                CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyFields(
                    new List<String>{question.Quote_Save_Field__c},
                    new List<String>(),
                    'Quote',
                    'Quote Save Field'
                );
                if (results.result == false) {
                    question.addError(results.errorMessage);
                }
            }

            // Default Field Value change
            if (question.Default_Field_Value__c != oldQuestion.Default_Field_Value__c &&
                question.Default_Field_Value__c != null
            ) {
                
                // Validate Default Field Value field
                CPQ_Record_Validation.ResultClass results = CPQ_Record_Validation.verifyObjectFieldPair(
                    question.Default_Field_Value__c,
                    new Map<String, String>{
                        'Account' => 'Account',
                        'Opportunity' => 'Opportunity',
                        'Quote' => 'Quote',
                        'Contract' => 'Contract',
                        'Profile' => 'Profile',
                        'UserRole' => 'UserRole',
                        'User' => 'User'
                    },
                    'Default Field Value'
                );
                if (results.result == false) {
                    question.addError(results.errorMessage);
                }
            }
        }
    }
}