SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/CPQ_Playbook__c.object-meta.xml
<CustomObject>
    <description>Set of deal questions for CPQ quote generation. Unique path for different opportunity types</description>
    <label>CPQ Playbook</label>
    <nameField>
        <label>CPQ Playbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Default_Term_in_Months__c.field-meta.xml
<CustomField>
    <fullName>Default_Term_in_Months__c</fullName>
    <description>Default term of quote in months</description>
    <inlineHelpText>Default term of quote in months</inlineHelpText>
    <label>Default Term (in Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Entitlement_Summary_Columns__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Summary_Columns__c</fullName>
    <description>Semicolon delineated list of field API names on the Contract_Entitlement__c object to be shown in the Entitlement Summary view in CPQ. Any Contract_Entitlement__c Custom Field API names are supported.</description>
    <inlineHelpText>Semicolon delineated list of field API names on the Contract_Entitlement__c object to be shown in the Entitlement Summary view in CPQ. Any Contract_Entitlement__c Custom Field API names are supported.</inlineHelpText>
    <label>Entitlement Summary Columns</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if playbook is active and should appear in CPQ</description>
    <inlineHelpText>Determines if playbook is active and should appear in CPQ</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Displayed label in CPQ</description>
    <inlineHelpText>Displayed label Users see in CPQ</inlineHelpText>
    <label>Label</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Pricebook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pricebook used for products added in playbook</description>
    <inlineHelpText>Pricebook from which products are pulled from for rules</inlineHelpText>
    <label>Pricebook</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>CPQ Playbooks</relationshipLabel>
    <relationshipName>CPQ_Playbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Product_Summary_Columns__c.field-meta.xml
<CustomField>
    <fullName>Product_Summary_Columns__c</fullName>
    <description>Semicolon delineated list of attribute names on the Product level to be shown in the Product Summary view in CPQ. The following CPQ attributes are valid: &apos;Product_Name&apos;, &apos;Start_Date&apos;, &apos;End_Date&apos;, &apos;Quantity&apos;, &apos;Discount&apos;, &apos;Unit_Price&apos;, &apos;List_Price&apos;, &apos;Sub_Total_Price&apos;, and &apos;Total_Price&apos;. Any QuoteLineItem Field API names are also supported in the event that CPQ is custom stamping said fields.</description>
    <inlineHelpText>List of attribute names on the Product level to be shown in the Product Summary view in CPQ. The following CPQ attributes are valid: &apos;Product_Name&apos;, &apos;Start_Date&apos;, &apos;End_Date&apos;, &apos;Quantity&apos;, &apos;Discount&apos;, &apos;Unit_Price&apos;, &apos;List_Price&apos;, &apos;Sub_Total_Price&apos;, and &apos;Total_Price&apos;. Any QuoteLineItem Field API names are also supported in the event that CPQ is custom stamping said fields.</inlineHelpText>
    <label>Product Summary Columns</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Proposal_Footer__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Footer__c</fullName>
    <description>Footer display for Proposal PDF</description>
    <inlineHelpText>Footer display for Proposal PDF (Will not appear on the first page)</inlineHelpText>
    <label>Proposal Footer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Proposal_Header__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Header__c</fullName>
    <description>Header display for Proposal PDF</description>
    <inlineHelpText>Header display for Proposal PDF (Will not appear on the first page)</inlineHelpText>
    <label>Proposal Header</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook__c/fields/Proposal_Header_Type__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Header_Type__c</fullName>
    <description>Determines if Proposal Header will display from an attached image or from the rich text field</description>
    <inlineHelpText>Determines if Proposal Header will display from an attached image or from the rich text field</inlineHelpText>
    <label>Proposal Header Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approval__c/CPQ_Playbook_Approval__c.object-meta.xml
<CustomObject>
    <description>Approvals governing allowed behavior of CPQ Playbook modifications</description>
    <label>CPQ Playbook Approval</label>
    <nameField>
        <label>CPQ Playbook Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approval__c/fields/CPQ_Playbook__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook__c</fullName>
    <description>Playbook in which this approval is enforced</description>
    <inlineHelpText>Playbook in which this approval is enforced</inlineHelpText>
    <label>CPQ Playbook</label>
    <referenceTo>CPQ_Playbook__c</referenceTo>
    <relationshipLabel>CPQ Playbook Approvals</relationshipLabel>
    <relationshipName>CPQ_Playbook_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approval__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if approval is active and should be enforced in playbook</description>
    <inlineHelpText>Determines if approval is active and should be enforced in playbook</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approval__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Label users see in CPQ for this approval</description>
    <inlineHelpText>Displayed label Users see in CPQ</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approval__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Reason users are shown for why this approval is being required</description>
    <inlineHelpText>Reason Users wee for why this approval is being required</inlineHelpText>
    <label>Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approver__c/CPQ_Playbook_Approver__c.object-meta.xml
<CustomObject>
    <description>Approver of a specific CPQ Playbook Approval</description>
    <label>CPQ Playbook Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Approvers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approver__c/fields/CPQ_Playbook_Approver_Group__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook_Approver_Group__c</fullName>
    <description>CPQ Playbook Approver Group in which Approver is needed</description>
    <inlineHelpText>Playbook Approver Group in which Approver is needed</inlineHelpText>
    <label>CPQ Playbook Approver Group</label>
    <referenceTo>CPQ_Playbook_Approver_Group__c</referenceTo>
    <relationshipLabel>CPQ Playbook Approvers</relationshipLabel>
    <relationshipName>CPQ_Playbook_Approvers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approver__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if approver is active and should be enforced in group</description>
    <inlineHelpText>Determines if approver is active and should be enforced in group</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approver_Group__c/CPQ_Playbook_Approver_Group__c.object-meta.xml
<CustomObject>
    <description>Object to house 1 or more CPQ Playbook Approver records</description>
    <label>CPQ Playbook Approver Group</label>
    <nameField>
        <label>Approver Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Playbook Approver Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approver_Group__c/fields/CPQ_Playbook_Approval__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook_Approval__c</fullName>
    <description>CPQ Playbook Approval in which the Approver Group is enforced</description>
    <inlineHelpText>Playbook Approval in which the group is enforced</inlineHelpText>
    <label>CPQ Playbook Approval</label>
    <referenceTo>CPQ_Playbook_Approval__c</referenceTo>
    <relationshipLabel>CPQ Playbook Approver Groups</relationshipLabel>
    <relationshipName>CPQ_Playbook_Approver_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Playbook_Approver_Group__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if approver group is active and should be enforced in approval</description>
    <inlineHelpText>Determines if approver group is active and should be enforced in approval</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Quote_Approval__c/CPQ_Quote_Approval__c.object-meta.xml
<CustomObject>
    <description>Quote level approval for CPQ Playbook Approval</description>
    <label>CPQ Quote Approval</label>
    <nameField>
        <label>CPQ Quote Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Quote Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Quote_Approval__c/fields/CPQ_Playbook_Approval__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook_Approval__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CPQ Playbook Approval for which the record tracks progress for the quote</description>
    <label>CPQ Playbook Approval</label>
    <referenceTo>CPQ_Playbook_Approval__c</referenceTo>
    <relationshipLabel>CPQ Quote Approvals</relationshipLabel>
    <relationshipName>CPQ_Quote_Approvals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Quote_Approval_Step__c/CPQ_Quote_Approval_Step__c.object-meta.xml
<CustomObject>
    <description>Quote level approval step for CPQ Playbook Approvals. Matches up to CPQ Playbook Approval Groups</description>
    <label>CPQ Quote Approval Step</label>
    <nameField>
        <label>CPQ Quote Approval Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Quote Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC_LD_Packages/CPQ/main/default/objects/CPQ_Quote_Approval_Step__c/fields/CPQ_Playbook_Approver_Group__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook_Approver_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Group that dictates how this step is approved</description>
    <label>CPQ Playbook Approver Group</label>
    <referenceTo>CPQ_Playbook_Approver_Group__c</referenceTo>
    <relationshipLabel>CPQ Quote Approval Steps</relationshipLabel>
    <relationshipName>CPQ_Quote_Approval_Steps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/objects-layouts/main/default/objects/Opportunity/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>IF(
AND(today()&gt;= Effective_service_date__c , today()&lt;= Actual_service_end_date__c ),TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/CPQ_Playbook__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Playbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Playbook used to configure quote in CPQ</description>
    <label>CPQ Playbook</label>
    <referenceTo>CPQ_Playbook__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/objects/Quote/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Latest end date of Quote Line Items</description>
    <label>End Date</label>
    <summarizedField>QuoteLineItem.End_Date__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

SFDC_LD_Packages/CPQ/main/default/classes/CPQ_Approval_Automation_Test.cls
/**
 * @author Tristan Moser
 * @date 4/19/2022
 *
 * @description Test class for:
 *  - CPQ_Quote_Approval_Step_Trigger
 *  - CPQ_Quote_Approval_Step_TriggerHandler
 *  - CPQ_Quote_Approval_Step_UpdatesUtil
 *  - CPQ_Quote_Approver_Trigger
 *  - CPQ_Quote_Approver_TriggerHandler
 *  - CPQ_Quote_Approver_UpdatesUtil
 *
 */
@isTest
public class CPQ_Approval_Automation_Test {

    /**
     * @description setup test data for use in test cases.
     **/
    @testSetup
    public static void setup() {

        // Pricebooks
        List<Pricebook2> testPricebooks = new List<Pricebook2>();
        testPricebooks.add(
            new Pricebook2(
                Id=Test.getStandardPricebookId(),
                Description = 'Standard Pricebook',
                IsActive = true
            )
        );
        update testPricebooks;


        // Playbooks
        List<CPQ_Playbook__c> testPlaybooks = new List<CPQ_Playbook__c>();
        testPlaybooks.add(
            new CPQ_Playbook__c(
                Default_Term_in_Months__c = 12,
                Entitlement_Summary_Columns__c = 'Quantity__c;End_Date__c',
                IsActive__c = true,
                Label__c = 'Playbook 1',
                Name = 'Playbook 1',
                Pricebook__c = testPricebooks[0].Id,
                Product_Summary_Columns__c = 'Quantity;End_Date',
                Proposal_Header__c = 'Header Text',
                Proposal_Header_Type__c = 'Text',
                Proposal_Footer__c = 'Footer Text'
            )
        );
        insert testPlaybooks;


        // Approvals
        List<CPQ_Playbook_Approval__c> testApprovals = new List<CPQ_Playbook_Approval__c>();
        testApprovals.add(
            new CPQ_Playbook_Approval__c(
                CPQ_Playbook__c = testPlaybooks[0].Id,
                IsActive__c = true,
                Label__c = 'Approval 1',
                Name = 'Approval 1',
                Reason__c = 'Approval Reason'
            )
        );
        insert testApprovals;


        // Approver Groups
        List<CPQ_Playbook_Approver_Group__c> testApproverGroups = new List<CPQ_Playbook_Approver_Group__c>();
        testApproverGroups.add(
            new CPQ_Playbook_Approver_Group__c(
                Approval_Order__c = 1,
                Approvers_Required__c = 1,
                CPQ_Playbook_Approval__c = testApprovals[0].Id,
                IsActive__c = true,
                Name = 'Group 1'
            )
        );
        testApproverGroups.add(
            new CPQ_Playbook_Approver_Group__c(
                Approval_Order__c = 2,
                Approvers_Required__c = 2,
                CPQ_Playbook_Approval__c = testApprovals[0].Id,
                IsActive__c = true,
                Name = 'Group 2'
            )
        );
        insert testApproverGroups;


        // Approvers
        List<CPQ_Playbook_Approver__c> testApprovers = new List<CPQ_Playbook_Approver__c>();
        testApprovers.add(
            new CPQ_Playbook_Approver__c(
                Approver__c = System.UserInfo.getUserId(),
                CPQ_Playbook_Approver_Group__c = testApproverGroups[0].Id,
                IsActive__c = true,
                Manager_Approver__c = false,
                Name = 'Approver 1'
            )
        );
        testApprovers.add(
            new CPQ_Playbook_Approver__c(
                Approver__c = System.UserInfo.getUserId(),
                CPQ_Playbook_Approver_Group__c = testApproverGroups[0].Id,
                IsActive__c = true,
                Manager_Approver__c = false,
                Name = 'Approver 2'
            )
        );
        testApprovers.add(
            new CPQ_Playbook_Approver__c(
                Approver__c = System.UserInfo.getUserId(),
                CPQ_Playbook_Approver_Group__c = testApproverGroups[1].Id,
                IsActive__c = true,
                Manager_Approver__c = false,
                Name = 'Approver 1'
            )
        );
        testApprovers.add(
            new CPQ_Playbook_Approver__c(
                Approver__c = System.UserInfo.getUserId(),
                CPQ_Playbook_Approver_Group__c = testApproverGroups[1].Id,
                IsActive__c = true,
                Manager_Approver__c = false,
                Name = 'Approver 2'
            )
        );
        insert testApprovers;


        // Account
        Account testAccount = new Account(
            Name = 'Test Account'
        );
        insert testAccount;


        // Opportunity
        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = testAccount.Id,
            StageName = 'Qualification', 
            CloseDate = Date.today()
        );
        insert testOpportunity;


        // Quote
        Quote testQuote  = new Quote(
            OpportunityId = testOpportunity.Id,
            Pricebook2Id = testPricebooks[0].Id,
            Name = 'Test Quote',
            Adjustment_of_Contract__c = null,
            Adjustment_Type__c = null,
            CPQ_Playbook__c = testPlaybooks[0].Id,
            IsClone__c = false,
            Playbook_Status__c = 'Complete'
        );
        insert testQuote;


        // Quote Approval
        CPQ_Quote_Approval__c testQuoteApproval = new CPQ_Quote_Approval__c(
            CPQ_Playbook_Approval__c = testApprovals[0].Id,
            Status__c = 'Pending',
            Quote__c = testQuote.Id
        );
        insert testQuoteApproval;


        // Quote Approval Steps
        List<CPQ_Quote_Approval_Step__c> testQuoteApprovalSteps = new List<CPQ_Quote_Approval_Step__c>();
        testQuoteApprovalSteps.add(
            new CPQ_Quote_Approval_Step__c(
                CPQ_Playbook_Approver_Group__c = testApproverGroups[0].Id,
                Status__c = 'Pending',
                CPQ_Quote_Approval__c = testQuoteApproval.Id
            )
        );
        testQuoteApprovalSteps.add(
            new CPQ_Quote_Approval_Step__c(
                CPQ_Playbook_Approver_Group__c = testApproverGroups[1].Id,
                Status__c = 'Pending',
                CPQ_Quote_Approval__c = testQuoteApproval.Id
            )
        );
        insert testQuoteApprovalSteps;


        // Quote Approvers
        List<CPQ_Quote_Approver__c> testQuoteApprovers = new List<CPQ_Quote_Approver__c>();
        testQuoteApprovers.add(
            new CPQ_Quote_Approver__c(
                CPQ_Quote_Approval_Step__c = testQuoteApprovalSteps[0].Id,
                CPQ_Playbook_Approver__c = testApprovers[0].Id,
                Status__c = 'Pending',
                Approver__c = testApprovers[0].Approver__c
            )
        );
        testQuoteApprovers.add(
            new CPQ_Quote_Approver__c(
                CPQ_Quote_Approval_Step__c = testQuoteApprovalSteps[0].Id,
                CPQ_Playbook_Approver__c = testApprovers[1].Id,
                Status__c = 'Pending',
                Approver__c = testApprovers[1].Approver__c
            )
        );
        testQuoteApprovers.add(
            new CPQ_Quote_Approver__c(
                CPQ_Quote_Approval_Step__c = testQuoteApprovalSteps[1].Id,
                CPQ_Playbook_Approver__c = testApprovers[2].Id,
                Status__c = 'Pending',
                Approver__c = testApprovers[2].Approver__c
            )
        );
        testQuoteApprovers.add(
            new CPQ_Quote_Approver__c(
                CPQ_Quote_Approval_Step__c = testQuoteApprovalSteps[1].Id,
                CPQ_Playbook_Approver__c = testApprovers[3].Id,
                Status__c = 'Pending',
                Approver__c = testApprovers[3].Approver__c
            )
        );
        insert testQuoteApprovers;

    }

    /**
     * @description Test to verify submitting approvers
     **/
    @isTest
    public static void testSubmitApprovers() {

        List<CPQ_Quote_Approver__c> testQuoteApprovers = [
            SELECT Id,
                Status__c
            FROM CPQ_Quote_Approver__c
            WHERE CPQ_Quote_Approval_Step__r.CPQ_Playbook_Approver_Group__r.Approval_Order__c = 1
        ];

        for (CPQ_Quote_Approver__c approver : testQuoteApprovers) {
            approver.Status__c = 'Submitted';
        }

        Test.startTest();

        update testQuoteApprovers;

        Test.stopTest();

        // Verify updates
        List<ProcessInstanceWorkItem> approvals = [
            SELECT Id,
                ProcessInstance.TargetObjectId
            FROM ProcessInstanceWorkItem
        ];

        System.assertEquals(2, approvals.size());
    }

    /**
     * @description Test to verify approve approver (enough to approve step)
     **/
    @isTest
    public static void testApproveApprover() {

        CPQ_Quote_Approver__c testQuoteApprover = [
            SELECT Id,
                CPQ_Quote_Approval_Step__c,
                Status__c
            FROM CPQ_Quote_Approver__c
            WHERE CPQ_Quote_Approval_Step__r.CPQ_Playbook_Approver_Group__r.Approval_Order__c = 1
            LIMIT 1
        ];

        testQuoteApprover.Status__c = 'Approved';

        Test.startTest();

        update testQuoteApprover;

        Test.stopTest();

        // Verify updates
        CPQ_Quote_Approval_Step__c testApprovalStep = [
            SELECT Id,
                Status__c
            FROM CPQ_Quote_Approval_Step__c
            WHERE Id =:testQuoteApprover.CPQ_Quote_Approval_Step__c
        ];
        System.assertEquals('Approved', testApprovalStep.Status__c);

        CPQ_Quote_Approver__c testOtherApproverStep1 = [
            SELECT Id,
                CPQ_Quote_Approval_Step__c,
                Status__c
            FROM CPQ_Quote_Approver__c
            WHERE CPQ_Quote_Approval_Step__r.CPQ_Playbook_Approver_Group__r.Approval_Order__c = 1 AND
                Id !=:testQuoteApprover.Id
            LIMIT 1
        ];
        System.assertEquals('Recalled', testOtherApproverStep1.Status__c);

        CPQ_Quote_Approval_Step__c testNextStep = [
            SELECT Id,
                Status__c
            FROM CPQ_Quote_Approval_Step__c
            WHERE Id !=:testQuoteApprover.CPQ_Quote_Approval_Step__c
        ];
        System.assertEquals('Submitted', testNextStep.Status__c);

        List<CPQ_Quote_Approver__c> testNextStepApprovers = [
            SELECT Id,
                CPQ_Quote_Approval_Step__c,
                Status__c
            FROM CPQ_Quote_Approver__c
            WHERE CPQ_Quote_Approval_Step__r.CPQ_Playbook_Approver_Group__r.Approval_Order__c = 2
        ];
        for (CPQ_Quote_Approver__c approver : testNextStepApprovers) {
            System.assertEquals('Submitted', approver.Status__c);
        }
    }

    /**
     * @description Test to verify approve approver (NOT enough to approve step)
     **/
    @isTest
    public static void testApproveApprover2() {

        CPQ_Quote_Approver__c testQuoteApprover = [
            SELECT Id,
                CPQ_Quote_Approval_Step__c,
                Status__c
            FROM CPQ_Quote_Approver__c
            WHERE CPQ_Quote_Approval_Step__r.CPQ_Playbook_Approver_Group__r.Approval_Order__c = 2
            LIMIT 1
        ];

        testQuoteApprover.Status__c = 'Approved';

        Test.startTest();

        update testQuoteApprover;

        Test.stopTest();

        // Verify updates
        CPQ_Quote_Approval_Step__c testApprovalStep = [
            SELECT Id,
                Status__c
            FROM CPQ_Quote_Approval_Step__c
            WHERE Id =:testQuoteApprover.CPQ_Quote_Approval_Step__c
        ];
        System.assertNotEquals('Approved', testApprovalStep.Status__c);
    }

    /**
     * @description Test to verify approve approver (enough to approve last step)
     **/
    @isTest
    public static void testApproveApprovers3() {

        List<CPQ_Quote_Approver__c> testQuoteApprovers = [
            SELECT Id,
                CPQ_Quote_Approval_Step__c,
                Status__c
            FROM CPQ_Quote_Approver__c
            WHERE CPQ_Quote_Approval_Step__r.CPQ_Playbook_Approver_Group__r.Approval_Order__c = 2
        ];

        for (CPQ_Quote_Approver__c approver : testQuoteApprovers) {
            approver.Status__c = 'Approved';
        }

        Test.startTest();

        update testQuoteApprovers;

        Test.stopTest();

        // Verify updates
        CPQ_Quote_Approval_Step__c testApprovalStep = [
            SELECT Id,
                Status__c
            FROM CPQ_Quote_Approval_Step__c
            WHERE Approval_Order__c = 2
        ];
        System.assertEquals('Approved', testApprovalStep.Status__c);

        CPQ_Quote_Approval__c testApproval = [
            SELECT Id,
                Status__c
            FROM CPQ_Quote_Approval__c
        ];
        System.assertEquals('Approved', testApproval.Status__c);
    }

    /**
     * @description Test to verify reject approver (enough to reject step)
     **/
    @isTest
    public static void testRejectApprover() {

        List<CPQ_Quote_Approver__c> testQuoteApprovers = [
            SELECT Id,
                CPQ_Quote_Approval_Step__c,
                Status__c
            FROM CPQ_Quote_Approver__c
            WHERE CPQ_Quote_Approval_Step__r.CPQ_Playbook_Approver_Group__r.Approval_Order__c = 1
        ];
        Id stepId;

        for (CPQ_Quote_Approver__c approver : testQuoteApprovers) {
            approver.Status__c = 'Rejected';
            stepId = approver.CPQ_Quote_Approval_Step__c;
        }

        Test.startTest();

        update testQuoteApprovers;

        Test.stopTest();

        // Verify updates
        CPQ_Quote_Approval_Step__c testApprovalStep = [
            SELECT Id,
                Status__c
            FROM CPQ_Quote_Approval_Step__c
            WHERE Id =:stepId
        ];
        System.assertEquals('Rejected', testApprovalStep.Status__c);

        CPQ_Quote_Approval_Step__c testNextStep = [
            SELECT Id,
                Status__c,
                (
                    SELECT Id,
                        Status__c
                    FROM CPQ_Quote_Approvers__r
                )
            FROM CPQ_Quote_Approval_Step__c
            WHERE Id !=:stepId
        ];
        System.assertEquals('Recalled', testNextStep.Status__c);
        for (CPQ_Quote_Approver__c approver : testNextStep.CPQ_Quote_Approvers__r) {
            System.assertEquals('Recalled', approver.Status__c);
        }

        CPQ_Quote_Approval__c testApproval = [
            SELECT Id,
                Status__c
            FROM CPQ_Quote_Approval__c
        ];
        System.assertEquals('Rejected', testApproval.Status__c);
    }

    /**
     * @description Test to verify reject approver (NOT enough to reject step)
     **/
    @isTest
    public static void testRejectApprover2() {

        CPQ_Quote_Approver__c testQuoteApprover = [
            SELECT Id,
                CPQ_Quote_Approval_Step__c,
                Status__c
            FROM CPQ_Quote_Approver__c
            WHERE CPQ_Quote_Approval_Step__r.CPQ_Playbook_Approver_Group__r.Approval_Order__c = 1
            LIMIT 1
        ];

        testQuoteApprover.Status__c = 'Rejected';

        Test.startTest();

        update testQuoteApprover;

        Test.stopTest();

        // Verify updates
        CPQ_Quote_Approval_Step__c testApprovalStep = [
            SELECT Id,
                Status__c
            FROM CPQ_Quote_Approval_Step__c
            WHERE Id =:testQuoteApprover.CPQ_Quote_Approval_Step__c
        ];
        System.assertNotEquals('Rejected', testApprovalStep.Status__c);

        CPQ_Quote_Approval_Step__c testNextStep = [
            SELECT Id,
                Status__c,
                (
                    SELECT Id,
                        Status__c
                    FROM CPQ_Quote_Approvers__r
                )
            FROM CPQ_Quote_Approval_Step__c
            WHERE Id !=:testQuoteApprover.CPQ_Quote_Approval_Step__c
        ];
        System.assertNotEquals('Recalled', testNextStep.Status__c);
        for (CPQ_Quote_Approver__c approver : testNextStep.CPQ_Quote_Approvers__r) {
            System.assertNotEquals('Recalled', approver.Status__c);
        }

        CPQ_Quote_Approval__c testApproval = [
            SELECT Id,
                Status__c
            FROM CPQ_Quote_Approval__c
        ];
        System.assertNotEquals('Rejected', testApproval.Status__c);
    }

    /**
     * @description Test to verify recall approver
     **/
    @isTest
    public static void testRecallApprover() {

        CPQ_Quote_Approver__c testQuoteApprover = [
            SELECT Id,
                CPQ_Quote_Approval_Step__c,
                Status__c
            FROM CPQ_Quote_Approver__c
            WHERE CPQ_Quote_Approval_Step__r.CPQ_Playbook_Approver_Group__r.Approval_Order__c = 1
            LIMIT 1
        ];

        testQuoteApprover.Status__c = 'Submitted';
        update testQuoteApprover;

        testQuoteApprover.Status__c = 'Recalled';
        CPQ_Quote_Approver_UpdatesUtil.runStepUpdates = true;

        Test.startTest();

        update testQuoteApprover;

        Test.stopTest();

        // Verify updates
        CPQ_Quote_Approval_Step__c testApprovalStep = [
            SELECT Id,
                Status__c
            FROM CPQ_Quote_Approval_Step__c
            WHERE Id =:testQuoteApprover.CPQ_Quote_Approval_Step__c
        ];
        System.assertEquals('Recalled', testApprovalStep.Status__c);

        List<ProcessInstanceWorkItem> approvals = new List<ProcessInstanceWorkItem>();
        approvals = [
            SELECT Id,
                ProcessInstance.TargetObjectId
            FROM ProcessInstanceWorkItem
        ];
        System.assertEquals(0, approvals.size());

        CPQ_Quote_Approval_Step__c testNextStep = [
            SELECT Id,
                Status__c,
                (
                    SELECT Id,
                        Status__c
                    FROM CPQ_Quote_Approvers__r
                )
            FROM CPQ_Quote_Approval_Step__c
            WHERE Id !=:testQuoteApprover.CPQ_Quote_Approval_Step__c
        ];
        System.assertEquals('Recalled', testNextStep.Status__c);
        for (CPQ_Quote_Approver__c approver : testNextStep.CPQ_Quote_Approvers__r) {
            System.assertEquals('Recalled', approver.Status__c);
        }

        CPQ_Quote_Approval__c testApproval = [
            SELECT Id,
                Status__c
            FROM CPQ_Quote_Approval__c
        ];
        System.assertEquals('Recalled', testApproval.Status__c);
    }

    /**
     * @description Test to verify approve approver
     **/
    @isTest
    public static void testApproveApproverSubmitted() {

        CPQ_Quote_Approver__c testQuoteApprover = [
            SELECT Id,
                CPQ_Quote_Approval_Step__c,
                Status__c
            FROM CPQ_Quote_Approver__c
            WHERE CPQ_Quote_Approval_Step__r.CPQ_Playbook_Approver_Group__r.Approval_Order__c = 1
            LIMIT 1
        ];

        testQuoteApprover.Status__c = 'Submitted';

        update testQuoteApprover;

        Test.startTest();

        testQuoteApprover.Decision_Reason__c = 'Test text';
        testQuoteApprover.Status__c = 'Approved';
        update testQuoteApprover;

        Test.stopTest();

        // Verify updates
        List<ProcessInstanceWorkItem> approvalWorkItems = [
            SELECT Id
            FROM ProcessInstanceWorkItem
            WHERE ProcessInstance.TargetObjectId =:testQuoteApprover.Id
        ];
        System.assertEquals(0, approvalWorkItems.size());
    }

    /**
     * @description Test to verify reject approver
     **/
    @isTest
    public static void testRejectApproverSubmitted() {

        CPQ_Quote_Approver__c testQuoteApprover = [
            SELECT Id,
                CPQ_Quote_Approval_Step__c,
                Status__c
            FROM CPQ_Quote_Approver__c
            WHERE CPQ_Quote_Approval_Step__r.CPQ_Playbook_Approver_Group__r.Approval_Order__c = 1
            LIMIT 1
        ];

        testQuoteApprover.Status__c = 'Submitted';

        update testQuoteApprover;

        Test.startTest();

        testQuoteApprover.Decision_Reason__c = 'Test text';
        testQuoteApprover.Status__c = 'Rejected';
        update testQuoteApprover;

        Test.stopTest();

        // Verify updates
        List<ProcessInstanceWorkItem> approvalWorkItems = [
            SELECT Id
            FROM ProcessInstanceWorkItem
            WHERE ProcessInstance.TargetObjectId =:testQuoteApprover.Id
        ];
        System.assertEquals(0, approvalWorkItems.size());
    }
}